import { createContext, useContext, useState, useCallback } from 'react';

export const LANGUAGES = [
  { value: 'en', label: 'English' },
  { value: 'hi', label: 'हिन्दी' },
  { value: 'ta', label: 'தமிழ்' },
  { value: 'te', label: 'తెలుగు' },
  { value: 'kn', label: 'ಕನ್ನಡ' },
  { value: 'ml', label: 'മലയാളം' },
];

const STORAGE_KEY = 'digivasool_language';

// UI string dictionary. Falls back to English for any key missing in a language.
const TRANSLATIONS = {
  en: {
    appName: 'VasoolPro', appTagline: 'Micro Finance System',
    navMain: 'Main', navFinance: 'Finance', navSystem: 'System', navCollector: 'Collector',
    dashboard: 'Dashboard', borrowers: 'Borrowers', collection: 'Collection', ledger: 'Ledger',
    expenses: 'Expenses', reports: 'Reports', staff: 'Staff', settings: 'Settings', recycleBin: 'Recycle Bin',
    collectPayment: 'Collect Payment', history: 'History', profile: 'Profile', transactions: 'Transactions',
    home: 'Home', collect: 'Collect', more: 'More', logout: 'Logout', language: 'Language',
    notifications: 'Notifications', today: 'Today', settingsComingSoon: 'Settings coming soon',
    welcomeBack: 'Welcome back to', helloGreeting: 'Hello', searchBorrowers: 'Search borrowers...',
    collectedToday: 'Collected Today', newLoan: 'New Loan', addBorrower: 'Add Borrower',
    todaysCollection: "Today's Collection", activeBorrowers: 'Active Borrowers',
    totalOutstanding: 'Total Outstanding', totalCollected: 'Total Collected',
    dueToday: 'Due Today', overdueAlerts: 'Overdue Alerts', seeAll: 'See all',
    borrowersAndLoans: 'Borrowers & Loans', allAreas: 'All Areas',
    welcome: 'Welcome!', howLogin: 'How do you want to log in?',
    imAdmin: "I'm an Admin", imCollector: "I'm a Collector",
    sendOtp: 'Send OTP', verifySignIn: 'Verify & Sign In', enterOtp: 'Enter OTP', back: 'Back',

    // Ledger
    ledgerPageTitle: 'Collection Ledger', entriesSuffix: 'entries', allStaff: 'All Staff', recordPayment: 'Record Payment',
    amountReceived: 'Amount Received (₹)', penaltyLateFee: 'Penalty / Late Fee (₹)', confirmPayment: 'Confirm Payment',
    totalDueToday: 'Total Due Today', collectedLabel: 'Collected', pendingLabel: 'Pending', collectionPercent: 'Collection %',
    collectionProgress: 'Collection Progress', daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', allDue: 'All Due',
    tableBorrower: 'Borrower', tablePhone: 'Phone', tableType: 'Type', tableDueAmount: 'Due Amount', tablePaid: 'Paid',
    tableStatus: 'Status', tableStaff: 'Staff', tableAction: 'Action', noInstallmentsDue: 'No installments due for this filter',
    statusPaid: 'Paid', statusPartial: 'Partial', statusPending: 'Pending', statusOverdue: 'Overdue',
    modeFull: 'Full', modePartial: 'Partial', modeAdvance: 'Advance',

    // Expenses
    expensesAndCapital: 'Expenses & Capital', businessFinancialHealth: 'Business financial health overview',
    logInvestment: 'Log Investment', addExpense: 'Add Expense', totalInvested: 'Total Invested', totalExpenses: 'Total Expenses',
    capitalInvestments: 'Capital Investments', logExpense: 'Log Expense', category: 'Category', amountRs: 'Amount (₹)',
    dateLabel: 'Date', descriptionLabel: 'Description', logCapitalInvestment: 'Log Capital Investment',
    amountInvested: 'Amount Invested (₹)', noteLabel: 'Note',

    // Reports
    financialReports: 'Financial Reports', analyticsExportCenter: 'Analytics and export center', excel: 'Excel', pdfReport: 'PDF Report',
    reportPL: 'Profit & Loss', reportPLDesc: 'Revenue and expenses', reportCollection: 'Collection Summary',
    reportCollectionDesc: 'Day-wise collection performance', reportPortfolio: 'Loan Portfolio',
    reportPortfolioDesc: 'Active loans by type and status', reportOverdue: 'Overdue Report',
    reportOverdueDesc: 'All overdue accounts and aging', grossRevenue: 'Gross Revenue',
    grossRevenueNote: 'Total interest + principal collected', totalExpensesNote: 'Salaries, fuel, office, misc',
    outstandingLabel: 'Outstanding', outstandingNote: 'Pending amount to recover', tableDay: 'Day', tableTarget: 'Target',
    tableAchievement: 'Achievement', tablePrincipal: 'Principal', tableTotalDue: 'Total Due', statusActive: 'Active',
    statusClosed: 'Closed', statusDefaulted: 'Defaulted', loansSuffix: 'Loans', noOverdueAccounts: 'No overdue accounts!',
    tableDueDate: 'Due Date', tableAmountDue: 'Amount Due', tableDaysOverdue: 'Days Overdue', daysSuffix: 'days',

    // Staff
    staffManagement: 'Staff Management', teamMembers: 'team members', rbacEnabled: 'RBAC enabled', addStaff: 'Add Staff',
    addStaffMember: 'Add Staff Member', fullNameRequired: 'Full Name *', role: 'Role', roleAdmin: 'Admin', roleManager: 'Manager',
    roleCollector: 'Collector', phone: 'Phone', monthlyTarget: 'Monthly Target (₹)', efficiency: 'Efficiency', target: 'Target',
    loans: 'Loans', rolePermissionMatrix: 'Role Permission Matrix', permission: 'Permission', permViewDashboard: 'View Dashboard',
    permCreateLoans: 'Create Loans', permCollectPayments: 'Collect Payments', permViewReports: 'View Reports & P&L',
    permManageStaff: 'Manage Staff', permDeleteRecords: 'Delete Records', permExportData: 'Export Data',
    permViewCapital: 'View Capital/Investment', recentAuditLog: 'Recent Audit Log',

    // Profile
    myProfile: 'My Profile', verified: 'Verified', contactInformation: 'Contact Information', emailAddress: 'Email Address',
    phoneNumber: 'Phone Number', homeAddress: 'Home Address', financeAndProofs: 'Finance & Proofs',
    linkedBankAccount: 'Linked Bank Account', mandatoryProofKyc: 'Mandatory Proof Copy (KYC)', notYetUploaded: 'Not yet uploaded',
    upload: 'Upload', loginHistory: 'Login History', signOutSafely: 'Sign Out Safely', loadingProfile: 'Loading profile...',

    // PhotoCapture
    uploadBtn: 'Upload', cameraBtn: 'Camera', removeBtn: 'Remove', takePhoto: 'Take Photo', retake: 'Retake',
    usePhoto: 'Use Photo', flip: 'Flip', capture: 'Capture',
    cameraNotSupported: 'Camera not supported on this device/browser. Please use Upload instead.',
    cameraPermissionDenied: 'Camera permission denied. Allow camera access or use Upload.',
    cameraAccessError: 'Could not access camera. Please use Upload instead.',
    addPhotoDefault: 'Add photo', addBorrowerPhoto: 'Add borrower photo (upload or camera)', addPhotoUploadCamera: 'Add photo (upload or camera)',

    // CollectionEntry
    selectBorrower: 'Select Borrower', noActiveLoans: 'No active loans. Provision members first.',
    searchNameLocation: 'Search name or location...', noMembersMatch: 'No members match your search.',
    capturePayment: 'Capture Payment', statusColon: 'Status:', recoveryProgress: 'Recovery Progress',
    principalAmount: 'Principal Amount', totalDueLabel: 'Total Due', recovered: 'Recovered',
    outstandingBalance: 'Outstanding Balance', paymentDetails: 'Payment Details', cashFlow: 'Cash Flow', upiGpay: 'UPI / GPay',
    processing: 'Processing...', record: 'Record', payment: 'Payment',

    // Transactions
    ledgerBook: 'Ledger Book', settled: 'Settled', principalColon: 'Principal:', paidColon: 'Paid:',
    noLedgerEntries: 'No ledger entries yet',

    // CollectPayment
    paymentRecorded: 'Payment Recorded!', savedSuccessfully: 'saved successfully', remainingBalance: 'Remaining Balance',
    loanFullyPaid: 'Loan Fully Paid!', sendWhatsappNotifications: 'Send WhatsApp Notifications',
    notifyAdminWhatsapp: 'Notify Admin on WhatsApp', confirmToBorrower: 'Confirm to Borrower', messagePreview: 'Message Preview',
    recordAnotherPayment: 'Record Another Payment', collectPaymentTitle: 'Collect Payment', asRole: 'as', sort: 'Sort',
    noActiveLoansFound: 'No active loans found.', noBorrowersMatch: 'No borrowers match your search.', balance: 'Balance',
    collectorYou: 'Collector (You)', notesOptional: 'Notes (optional)', saving: 'Saving...', cash: 'Cash', gpayUpi: 'GPay / UPI',
    noPhone: 'No phone', dueColon: 'Due:', callBorrower: 'Call borrower', call: 'Call', paymentEntry: 'Payment Entry',

    // CollectorHistory
    myCollections: 'My Collections', allPaymentsRecorded: 'All payments you have recorded', entriesLabel: 'Entries',
    noCollectionsYet: 'No collections recorded yet. Start collecting!', loadingHistory: 'Loading your collection history...',

    // Members — Add Borrower + Loan modal
    newBorrowerLoan: 'New Borrower + Loan', requiredNote: '* = required', personalDetails: 'Personal Details',
    fullName: 'Full Name *', shopBusinessName: 'Shop / Business Name', primaryMobile: 'Primary Mobile *',
    alternateMobile: 'Alternate Mobile', areaInCoimbatore: 'Area in Coimbatore *', verifyPhoneOtp: 'Verify Phone with OTP (optional)',
    phoneVerified: 'Phone Verified', email: 'Email', aadhaarNumber: 'Aadhaar Number', address: 'Address',
    guarantorDetails: 'Guarantor Details', guarantorName: 'Guarantor Name', guarantorPhone: 'Guarantor Phone',
    guarantorAddress: 'Guarantor Address', loanDetails: 'Loan Details', loanAmount: 'Loan Amount (₹) *',
    charges: 'Charges (%)', chargesAmount: 'Charges Amount (₹)', auto: 'auto', startDate: 'Start Date *', dueDate: 'Due Date *',
    chargesAndFees: 'Charges & Fees (₹)', autoSplitNote: 'Auto-split from Charges — Interest 18%, Field Verification 31%, Document Fee 30%, Processing Fee 21%. Adjust below if this loan needs different amounts.',
    fieldVerification: 'Field Verification', documentFee: 'Document Fee', processingFee: 'Processing Fee', chargeInterest: 'Interest',
    breakdown: 'BREAKDOWN', principalLoanAmount: 'Principal (Loan Amount)', ofWhich: 'of which',
    deductedUpfront: 'Deducted upfront from principal', cashDisbursedToBorrower: 'Cash Disbursed to Borrower',
    totalDueRepayable: 'Total Due (Repayable)', repaymentSchedule: 'Repayment Schedule', amountPerInstallment: 'Amount per installment (₹)',
    disbursementSmsLanguage: 'Disbursement SMS Language', autoWhatsappReminders: 'Auto WhatsApp Reminders',
    confirmLoanDisbursal: 'Confirm Loan Disbursal', creating: 'Creating...',
    existingBorrower: 'Existing Borrower', newBorrower: 'New Borrower', selectZone: 'Select area…',
    mergeBorrowers: 'Merge Borrowers', merge: 'Merge', mergeSelected: 'Merge Selected Borrowers',
    noBorrowersYet: 'No borrowers yet. Tap + to add one.', highestBalance: 'Highest Balance', nameAZ: 'Name A-Z',
    byArea: 'By Coimbatore Area', newestFirst: 'Newest First', due: 'Due', paidSuffix: 'paid',
    loanDisbursed: 'Loan Disbursed!', borrowerAccountNumber: 'Borrower Account Number', done: 'Done',
    noPhoneSmsUnavailable: 'No phone number on file — SMS not available.',
    freqCustom: 'Custom', freqDailyDesc: 'Collected every day', freqWeeklyDesc: 'Once a week',
    freqMonthlyDesc: 'Once a month', freqCustomDesc: 'Set your own amount',
    otpSending: 'Sending…', sendOtpToVerifyPhone: 'Send OTP to verify phone', testOtpLabel: 'Test OTP:',
    otpVerifying: 'Verifying…', verifyOtpBtn: 'Verify OTP',
    mergeBorrowersDesc: 'Select exactly 2 borrowers to merge. Their loan records will be combined under the first selected.',
    outstandingColon: 'Outstanding:', disbursedTo: 'disbursed to', disbursementSms: 'Disbursement SMS',
    sendSmsToBorrower: 'Send SMS to Borrower',
  },
  hi: {
    appName: 'वासूलप्रो', appTagline: 'माइक्रो फाइनेंस सिस्टम',
    navMain: 'मुख्य', navFinance: 'वित्त', navSystem: 'सिस्टम', navCollector: 'कलेक्टर',
    dashboard: 'डैशबोर्ड', borrowers: 'उधारकर्ता', collection: 'वसूली', ledger: 'खाता-बही',
    expenses: 'खर्च', reports: 'रिपोर्ट', staff: 'स्टाफ', settings: 'सेटिंग्स',
    collectPayment: 'भुगतान लें', history: 'इतिहास', profile: 'प्रोफ़ाइल', transactions: 'लेन-देन',
    home: 'होम', collect: 'वसूली', more: 'और', logout: 'लॉग आउट', language: 'भाषा',
    notifications: 'सूचनाएं', today: 'आज', settingsComingSoon: 'सेटिंग्स जल्द आ रही हैं',
    welcomeBack: 'में आपका स्वागत है', helloGreeting: 'नमस्ते', searchBorrowers: 'उधारकर्ता खोजें...',
    collectedToday: 'आज की वसूली', newLoan: 'नया ऋण', addBorrower: 'उधारकर्ता जोड़ें',
    todaysCollection: 'आज की वसूली', activeBorrowers: 'सक्रिय उधारकर्ता',
    totalOutstanding: 'कुल बकाया', totalCollected: 'कुल वसूली',
    dueToday: 'आज देय', overdueAlerts: 'अतिदेय चेतावनी', seeAll: 'सभी देखें',
    borrowersAndLoans: 'उधारकर्ता और ऋण', allAreas: 'सभी क्षेत्र',
    welcome: 'स्वागत है!', howLogin: 'आप कैसे लॉग इन करना चाहते हैं?',
    imAdmin: 'मैं एडमिन हूं', imCollector: 'मैं कलेक्टर हूं',
    sendOtp: 'ओटीपी भेजें', verifySignIn: 'सत्यापित करें और साइन इन करें', enterOtp: 'ओटीपी दर्ज करें', back: 'वापस',

    ledgerPageTitle: 'वसूली खाता-बही', entriesSuffix: 'प्रविष्टियाँ', allStaff: 'सभी स्टाफ', recordPayment: 'भुगतान दर्ज करें',
    amountReceived: 'प्राप्त राशि (₹)', penaltyLateFee: 'जुर्माना / विलंब शुल्क (₹)', confirmPayment: 'भुगतान की पुष्टि करें',
    totalDueToday: 'आज कुल देय', collectedLabel: 'वसूला गया', pendingLabel: 'लंबित', collectionPercent: 'वसूली %',
    collectionProgress: 'वसूली प्रगति', daily: 'दैनिक', weekly: 'साप्ताहिक', monthly: 'मासिक', allDue: 'सभी देय',
    tableBorrower: 'उधारकर्ता', tablePhone: 'फोन', tableType: 'प्रकार', tableDueAmount: 'देय राशि', tablePaid: 'भुगतान',
    tableStatus: 'स्थिति', tableStaff: 'स्टाफ', tableAction: 'कार्रवाई', noInstallmentsDue: 'इस फ़िल्टर के लिए कोई किस्त देय नहीं',
    statusPaid: 'भुगतान', statusPartial: 'आंशिक', statusPending: 'लंबित', statusOverdue: 'अतिदेय',
    modeFull: 'पूर्ण', modePartial: 'आंशिक', modeAdvance: 'अग्रिम',

    expensesAndCapital: 'खर्च और पूंजी', businessFinancialHealth: 'व्यवसाय की वित्तीय स्थिति का अवलोकन',
    logInvestment: 'निवेश दर्ज करें', addExpense: 'खर्च जोड़ें', totalInvested: 'कुल निवेश', totalExpenses: 'कुल खर्च',
    capitalInvestments: 'पूंजी निवेश', logExpense: 'खर्च दर्ज करें', category: 'श्रेणी', amountRs: 'राशि (₹)',
    dateLabel: 'तिथि', descriptionLabel: 'विवरण', logCapitalInvestment: 'पूंजी निवेश दर्ज करें',
    amountInvested: 'निवेशित राशि (₹)', noteLabel: 'टिप्पणी',

    financialReports: 'वित्तीय रिपोर्ट', analyticsExportCenter: 'विश्लेषण और निर्यात केंद्र', excel: 'एक्सेल', pdfReport: 'पीडीएफ रिपोर्ट',
    reportPL: 'लाभ और हानि', reportPLDesc: 'राजस्व और खर्च', reportCollection: 'वसूली सारांश',
    reportCollectionDesc: 'दिन-वार वसूली प्रदर्शन', reportPortfolio: 'ऋण पोर्टफोलियो',
    reportPortfolioDesc: 'प्रकार और स्थिति के अनुसार सक्रिय ऋण', reportOverdue: 'अतिदेय रिपोर्ट',
    reportOverdueDesc: 'सभी अतिदेय खाते और एजिंग', grossRevenue: 'सकल राजस्व',
    grossRevenueNote: 'कुल ब्याज + मूलधन वसूला गया', totalExpensesNote: 'वेतन, ईंधन, कार्यालय, विविध',
    outstandingLabel: 'बकाया', outstandingNote: 'वसूल करने के लिए लंबित राशि', tableDay: 'दिन', tableTarget: 'लक्ष्य',
    tableAchievement: 'उपलब्धि', tablePrincipal: 'मूलधन', tableTotalDue: 'कुल देय', statusActive: 'सक्रिय',
    statusClosed: 'बंद', statusDefaulted: 'डिफ़ॉल्ट', loansSuffix: 'ऋण', noOverdueAccounts: 'कोई अतिदेय खाता नहीं!',
    tableDueDate: 'देय तिथि', tableAmountDue: 'देय राशि', tableDaysOverdue: 'विलंब दिन', daysSuffix: 'दिन',

    staffManagement: 'स्टाफ प्रबंधन', teamMembers: 'टीम सदस्य', rbacEnabled: 'RBAC सक्षम', addStaff: 'स्टाफ जोड़ें',
    addStaffMember: 'स्टाफ सदस्य जोड़ें', fullNameRequired: 'पूरा नाम *', role: 'भूमिका', roleAdmin: 'एडमिन', roleManager: 'मैनेजर',
    roleCollector: 'कलेक्टर', phone: 'फोन', monthlyTarget: 'मासिक लक्ष्य (₹)', efficiency: 'दक्षता', target: 'लक्ष्य',
    loans: 'ऋण', rolePermissionMatrix: 'भूमिका अनुमति मैट्रिक्स', permission: 'अनुमति', permViewDashboard: 'डैशबोर्ड देखें',
    permCreateLoans: 'ऋण बनाएं', permCollectPayments: 'भुगतान वसूलें', permViewReports: 'रिपोर्ट और लाभ-हानि देखें',
    permManageStaff: 'स्टाफ प्रबंधित करें', permDeleteRecords: 'रिकॉर्ड हटाएं', permExportData: 'डेटा निर्यात करें',
    permViewCapital: 'पूंजी/निवेश देखें', recentAuditLog: 'हाल की ऑडिट लॉग',

    myProfile: 'मेरी प्रोफ़ाइल', verified: 'सत्यापित', contactInformation: 'संपर्क जानकारी', emailAddress: 'ईमेल पता',
    phoneNumber: 'फोन नंबर', homeAddress: 'घर का पता', financeAndProofs: 'वित्त और प्रमाण',
    linkedBankAccount: 'लिंक्ड बैंक खाता', mandatoryProofKyc: 'अनिवार्य प्रमाण प्रति (KYC)', notYetUploaded: 'अभी अपलोड नहीं हुआ',
    upload: 'अपलोड करें', loginHistory: 'लॉगिन इतिहास', signOutSafely: 'सुरक्षित रूप से साइन आउट करें', loadingProfile: 'प्रोफ़ाइल लोड हो रही है...',

    uploadBtn: 'अपलोड करें', cameraBtn: 'कैमरा', removeBtn: 'हटाएं', takePhoto: 'फोटो लें', retake: 'फिर से लें',
    usePhoto: 'फोटो का उपयोग करें', flip: 'पलटें', capture: 'कैप्चर करें',
    cameraNotSupported: 'इस डिवाइस/ब्राउज़र पर कैमरा समर्थित नहीं है। कृपया अपलोड का उपयोग करें।',
    cameraPermissionDenied: 'कैमरा अनुमति अस्वीकृत। कैमरा एक्सेस दें या अपलोड का उपयोग करें।',
    cameraAccessError: 'कैमरा एक्सेस नहीं हो सका। कृपया अपलोड का उपयोग करें।',
    addPhotoDefault: 'फोटो जोड़ें', addBorrowerPhoto: 'उधारकर्ता की फोटो जोड़ें (अपलोड या कैमरा)', addPhotoUploadCamera: 'फोटो जोड़ें (अपलोड या कैमरा)',

    selectBorrower: 'उधारकर्ता चुनें', noActiveLoans: 'कोई सक्रिय ऋण नहीं। पहले सदस्य जोड़ें।',
    searchNameLocation: 'नाम या स्थान खोजें...', noMembersMatch: 'आपकी खोज से कोई सदस्य मेल नहीं खाता।',
    capturePayment: 'भुगतान दर्ज करें', statusColon: 'स्थिति:', recoveryProgress: 'वसूली प्रगति',
    principalAmount: 'मूलधन राशि', totalDueLabel: 'कुल देय', recovered: 'वसूला गया',
    outstandingBalance: 'बकाया शेष', paymentDetails: 'भुगतान विवरण', cashFlow: 'नकद प्रवाह', upiGpay: 'UPI / GPay',
    processing: 'प्रोसेस हो रहा है...', record: 'दर्ज करें', payment: 'भुगतान',

    ledgerBook: 'खाता-बही', settled: 'चुकता', principalColon: 'मूलधन:', paidColon: 'भुगतान:',
    noLedgerEntries: 'अभी कोई खाता-बही प्रविष्टि नहीं',

    paymentRecorded: 'भुगतान दर्ज हुआ!', savedSuccessfully: 'सफलतापूर्वक सहेजा गया', remainingBalance: 'शेष राशि',
    loanFullyPaid: 'ऋण पूरी तरह चुकाया गया!', sendWhatsappNotifications: 'व्हाट्सएप सूचनाएं भेजें',
    notifyAdminWhatsapp: 'व्हाट्सएप पर एडमिन को सूचित करें', confirmToBorrower: 'उधारकर्ता को पुष्टि करें', messagePreview: 'संदेश पूर्वावलोकन',
    recordAnotherPayment: 'एक और भुगतान दर्ज करें', collectPaymentTitle: 'भुगतान लें', asRole: 'के रूप में', sort: 'क्रमबद्ध करें',
    noActiveLoansFound: 'कोई सक्रिय ऋण नहीं मिला।', noBorrowersMatch: 'आपकी खोज से कोई उधारकर्ता मेल नहीं खाता।', balance: 'शेष',
    collectorYou: 'कलेक्टर (आप)', notesOptional: 'टिप्पणी (वैकल्पिक)', saving: 'सहेजा जा रहा है...', cash: 'नकद', gpayUpi: 'GPay / UPI',
    noPhone: 'फोन नहीं', dueColon: 'देय:', callBorrower: 'उधारकर्ता को कॉल करें', call: 'कॉल', paymentEntry: 'भुगतान प्रविष्टि',

    myCollections: 'मेरी वसूली', allPaymentsRecorded: 'आपके द्वारा दर्ज सभी भुगतान', entriesLabel: 'प्रविष्टियाँ',
    noCollectionsYet: 'अभी तक कोई वसूली दर्ज नहीं। वसूली शुरू करें!', loadingHistory: 'आपका वसूली इतिहास लोड हो रहा है...',

    newBorrowerLoan: 'नया उधारकर्ता + ऋण', requiredNote: '* = आवश्यक', personalDetails: 'व्यक्तिगत विवरण',
    fullName: 'पूरा नाम *', shopBusinessName: 'दुकान / व्यवसाय का नाम', primaryMobile: 'प्राथमिक मोबाइल *',
    alternateMobile: 'वैकल्पिक मोबाइल', areaInCoimbatore: 'कोयंबटूर में क्षेत्र *', verifyPhoneOtp: 'ओटीपी से फोन सत्यापित करें (वैकल्पिक)',
    phoneVerified: 'फोन सत्यापित', email: 'ईमेल', aadhaarNumber: 'आधार नंबर', address: 'पता',
    guarantorDetails: 'गारंटर विवरण', guarantorName: 'गारंटर का नाम', guarantorPhone: 'गारंटर का फोन',
    guarantorAddress: 'गारंटर का पता', loanDetails: 'ऋण विवरण', loanAmount: 'ऋण राशि (₹) *',
    charges: 'शुल्क (%)', chargesAmount: 'शुल्क राशि (₹)', auto: 'स्वतः', startDate: 'प्रारंभ तिथि *', dueDate: 'देय तिथि *',
    chargesAndFees: 'शुल्क और फीस (₹)', autoSplitNote: 'शुल्क से स्वतः विभाजित — ब्याज 18%, फील्ड वेरिफिकेशन 31%, दस्तावेज़ शुल्क 30%, प्रोसेसिंग शुल्क 21%। यदि इस ऋण को अलग राशि चाहिए तो नीचे समायोजित करें।',
    fieldVerification: 'फील्ड वेरिफिकेशन', documentFee: 'दस्तावेज़ शुल्क', processingFee: 'प्रोसेसिंग शुल्क',
    breakdown: 'विवरण', principalLoanAmount: 'मूलधन (ऋण राशि)', ofWhich: 'जिसमें से',
    deductedUpfront: 'मूलधन से पहले ही काटा गया', cashDisbursedToBorrower: 'उधारकर्ता को दिया गया नकद',
    totalDueRepayable: 'कुल देय (चुकाने योग्य)', repaymentSchedule: 'भुगतान अनुसूची', amountPerInstallment: 'प्रति किस्त राशि (₹)',
    disbursementSmsLanguage: 'वितरण एसएमएस भाषा', autoWhatsappReminders: 'स्वतः व्हाट्सएप रिमाइंडर',
    confirmLoanDisbursal: 'ऋण वितरण की पुष्टि करें', creating: 'बनाया जा रहा है...',
    existingBorrower: 'मौजूदा उधारकर्ता', newBorrower: 'नया उधारकर्ता', selectZone: 'क्षेत्र चुनें…',
    mergeBorrowers: 'उधारकर्ताओं को मर्ज करें', merge: 'मर्ज करें', mergeSelected: 'चयनित उधारकर्ताओं को मर्ज करें',
    noBorrowersYet: 'अभी तक कोई उधारकर्ता नहीं। जोड़ने के लिए + दबाएं।', highestBalance: 'सर्वाधिक शेष', nameAZ: 'नाम A-Z',
    byArea: 'कोयंबटूर क्षेत्र अनुसार', newestFirst: 'नवीनतम पहले', due: 'देय', paidSuffix: 'भुगतान हुआ',
    loanDisbursed: 'ऋण वितरित हुआ!', borrowerAccountNumber: 'उधारकर्ता खाता संख्या', done: 'हो गया',
    noPhoneSmsUnavailable: 'फ़ोन नंबर उपलब्ध नहीं — एसएमएस संभव नहीं।',
    freqCustom: 'कस्टम', freqDailyDesc: 'रोज़ वसूला जाता है', freqWeeklyDesc: 'सप्ताह में एक बार',
    freqMonthlyDesc: 'महीने में एक बार', freqCustomDesc: 'अपनी राशि खुद तय करें',
    otpSending: 'भेजा जा रहा है…', sendOtpToVerifyPhone: 'फोन सत्यापित करने के लिए ओटीपी भेजें', testOtpLabel: 'टेस्ट ओटीपी:',
    otpVerifying: 'सत्यापित हो रहा है…', verifyOtpBtn: 'ओटीपी सत्यापित करें',
    mergeBorrowersDesc: 'मर्ज करने के लिए बिल्कुल 2 उधारकर्ता चुनें। उनके ऋण रिकॉर्ड पहले चुने गए के अंतर्गत मिला दिए जाएंगे।',
    outstandingColon: 'बकाया:', disbursedTo: 'को वितरित किया गया', disbursementSms: 'वितरण एसएमएस',
    sendSmsToBorrower: 'उधारकर्ता को एसएमएस भेजें',
  },
  ta: {
    appName: 'வசூல்ப்ரோ', appTagline: 'மைக்ரோ ஃபைனான்ஸ் சிஸ்டம்',
    navMain: 'முதன்மை', navFinance: 'நிதி', navSystem: 'கணினி', navCollector: 'கலெக்டர்',
    dashboard: 'டாஷ்போர்டு', borrowers: 'கடன் வாங்குபவர்கள்', collection: 'வசூல்', ledger: 'கணக்கு புத்தகம்',
    expenses: 'செலவுகள்', reports: 'அறிக்கைகள்', staff: 'ஊழியர்', settings: 'அமைப்புகள்',
    collectPayment: 'பணம் வசூலி', history: 'வரலாறு', profile: 'சுயவிவரம்', transactions: 'பரிவர்த்தனைகள்',
    home: 'முகப்பு', collect: 'வசூல்', more: 'மேலும்', logout: 'வெளியேறு', language: 'மொழி',
    notifications: 'அறிவிப்புகள்', today: 'இன்று', settingsComingSoon: 'அமைப்புகள் விரைவில் வரும்',
    welcomeBack: 'க்கு மீண்டும் வரவேற்கிறோம்', helloGreeting: 'வணக்கம்', searchBorrowers: 'கடன் வாங்குபவர்களைத் தேடு...',
    collectedToday: 'இன்று வசூலானது', newLoan: 'புதிய கடன்', addBorrower: 'கடன் வாங்குபவரைச் சேர்',
    todaysCollection: 'இன்றைய வசூல்', activeBorrowers: 'செயலில் உள்ள கடன் வாங்குபவர்கள்',
    totalOutstanding: 'மொத்த நிலுவை', totalCollected: 'மொத்த வசூல்',
    dueToday: 'இன்று செலுத்த வேண்டியது', overdueAlerts: 'தாமத எச்சரிக்கைகள்', seeAll: 'அனைத்தையும் காண்க',
    borrowersAndLoans: 'கடன் வாங்குபவர்கள் மற்றும் கடன்கள்', allAreas: 'அனைத்து பகுதிகள்',
    welcome: 'வரவேற்கிறோம்!', howLogin: 'நீங்கள் எப்படி உள்நுழைய விரும்புகிறீர்கள்?',
    imAdmin: 'நான் நிர்வாகி', imCollector: 'நான் கலெக்டர்',
    sendOtp: 'OTP அனுப்பு', verifySignIn: 'சரிபார்த்து உள்நுழை', enterOtp: 'OTP ஐ உள்ளிடவும்', back: 'பின்',

    ledgerPageTitle: 'வசூல் கணக்கு புத்தகம்', entriesSuffix: 'பதிவுகள்', allStaff: 'அனைத்து ஊழியர்கள்', recordPayment: 'பணம் பதிவு செய்',
    amountReceived: 'பெறப்பட்ட தொகை (₹)', penaltyLateFee: 'அபராதம் / தாமத கட்டணம் (₹)', confirmPayment: 'பணம் செலுத்தலை உறுதிப்படுத்து',
    totalDueToday: 'இன்று மொத்தம் செலுத்த வேண்டியது', collectedLabel: 'வசூலானது', pendingLabel: 'நிலுவை', collectionPercent: 'வசூல் %',
    collectionProgress: 'வசூல் முன்னேற்றம்', daily: 'தினசரி', weekly: 'வாராந்திர', monthly: 'மாதாந்திர', allDue: 'அனைத்து நிலுவை',
    tableBorrower: 'கடன் வாங்குபவர்', tablePhone: 'தொலைபேசி', tableType: 'வகை', tableDueAmount: 'செலுத்த வேண்டிய தொகை', tablePaid: 'செலுத்தியது',
    tableStatus: 'நிலை', tableStaff: 'ஊழியர்', tableAction: 'செயல்', noInstallmentsDue: 'இந்த வடிகட்டிக்கு தவணைகள் எதுவும் இல்லை',
    statusPaid: 'செலுத்தப்பட்டது', statusPartial: 'பகுதி', statusPending: 'நிலுவை', statusOverdue: 'தாமதம்',
    modeFull: 'முழு', modePartial: 'பகுதி', modeAdvance: 'முன்பணம்',

    expensesAndCapital: 'செலவுகள் மற்றும் மூலதனம்', businessFinancialHealth: 'வணிக நிதி நிலைமையின் மேலோட்டம்',
    logInvestment: 'முதலீட்டைப் பதிவு செய்', addExpense: 'செலவைச் சேர்', totalInvested: 'மொத்த முதலீடு', totalExpenses: 'மொத்த செலவுகள்',
    capitalInvestments: 'மூலதன முதலீடுகள்', logExpense: 'செலவைப் பதிவு செய்', category: 'வகை', amountRs: 'தொகை (₹)',
    dateLabel: 'தேதி', descriptionLabel: 'விளக்கம்', logCapitalInvestment: 'மூலதன முதலீட்டைப் பதிவு செய்',
    amountInvested: 'முதலீடு செய்யப்பட்ட தொகை (₹)', noteLabel: 'குறிப்பு',

    financialReports: 'நிதி அறிக்கைகள்', analyticsExportCenter: 'பகுப்பாய்வு மற்றும் ஏற்றுமதி மையம்', excel: 'எக்செல்', pdfReport: 'PDF அறிக்கை',
    reportPL: 'இலாப நஷ்டம்', reportPLDesc: 'வருவாய் மற்றும் செலவுகள்', reportCollection: 'வசூல் சுருக்கம்',
    reportCollectionDesc: 'நாள்வாரி வசூல் செயல்திறன்', reportPortfolio: 'கடன் போர்ட்·ஃபோலியோ',
    reportPortfolioDesc: 'வகை மற்றும் நிலை அடிப்படையில் செயலில் உள்ள கடன்கள்', reportOverdue: 'தாமத அறிக்கை',
    reportOverdueDesc: 'அனைத்து தாமதமான கணக்குகள் மற்றும் காலம்', grossRevenue: 'மொத்த வருவாய்',
    grossRevenueNote: 'மொத்த வட்டி + அசல் வசூலிக்கப்பட்டது', totalExpensesNote: 'சம்பளம், எரிபொருள், அலுவலகம், இதர',
    outstandingLabel: 'நிலுவை', outstandingNote: 'மீட்க வேண்டிய நிலுவைத் தொகை', tableDay: 'நாள்', tableTarget: 'இலக்கு',
    tableAchievement: 'சாதனை', tablePrincipal: 'அசல்', tableTotalDue: 'மொத்த நிலுவை', statusActive: 'செயலில்',
    statusClosed: 'முடிந்தது', statusDefaulted: 'தவறியது', loansSuffix: 'கடன்கள்', noOverdueAccounts: 'தாமதமான கணக்குகள் இல்லை!',
    tableDueDate: 'செலுத்த வேண்டிய தேதி', tableAmountDue: 'செலுத்த வேண்டிய தொகை', tableDaysOverdue: 'தாமத நாட்கள்', daysSuffix: 'நாட்கள்',

    staffManagement: 'ஊழியர் மேலாண்மை', teamMembers: 'குழு உறுப்பினர்கள்', rbacEnabled: 'RBAC இயக்கப்பட்டது', addStaff: 'ஊழியரைச் சேர்',
    addStaffMember: 'ஊழியர் உறுப்பினரைச் சேர்', fullNameRequired: 'முழுப்பெயர் *', role: 'பணி', roleAdmin: 'நிர்வாகி', roleManager: 'மேலாளர்',
    roleCollector: 'கலெக்டர்', phone: 'தொலைபேசி', monthlyTarget: 'மாத இலக்கு (₹)', efficiency: 'திறன்', target: 'இலக்கு',
    loans: 'கடன்கள்', rolePermissionMatrix: 'பணி அனுமதி அட்டவணை', permission: 'அனுமதி', permViewDashboard: 'டாஷ்போர்டைக் காண்க',
    permCreateLoans: 'கடன்களை உருவாக்கு', permCollectPayments: 'பணம் வசூலி', permViewReports: 'அறிக்கைகள் & இலாப நஷ்டத்தைக் காண்க',
    permManageStaff: 'ஊழியரை நிர்வகி', permDeleteRecords: 'பதிவுகளை நீக்கு', permExportData: 'தரவை ஏற்றுமதி செய்',
    permViewCapital: 'மூலதனம்/முதலீட்டைக் காண்க', recentAuditLog: 'சமீபத்திய தணிக்கை பதிவு',

    myProfile: 'எனது சுயவிவரம்', verified: 'சரிபார்க்கப்பட்டது', contactInformation: 'தொடர்பு தகவல்', emailAddress: 'மின்னஞ்சல் முகவரி',
    phoneNumber: 'தொலைபேசி எண்', homeAddress: 'வீட்டு முகவரி', financeAndProofs: 'நிதி மற்றும் ஆவணங்கள்',
    linkedBankAccount: 'இணைக்கப்பட்ட வங்கி கணக்கு', mandatoryProofKyc: 'கட்டாய ஆவண நகல் (KYC)', notYetUploaded: 'இன்னும் பதிவேற்றப்படவில்லை',
    upload: 'பதிவேற்று', loginHistory: 'உள்நுழைவு வரலாறு', signOutSafely: 'பாதுகாப்பாக வெளியேறு', loadingProfile: 'சுயவிவரம் ஏற்றப்படுகிறது...',

    uploadBtn: 'பதிவேற்று', cameraBtn: 'கேமரா', removeBtn: 'நீக்கு', takePhoto: 'புகைப்படம் எடு', retake: 'மீண்டும் எடு',
    usePhoto: 'புகைப்படத்தைப் பயன்படுத்து', flip: 'திருப்பு', capture: 'படம் பிடி',
    cameraNotSupported: 'இந்த சாதனம்/உலாவியில் கேமரா ஆதரிக்கப்படவில்லை. தயவுசெய்து பதிவேற்றத்தைப் பயன்படுத்தவும்.',
    cameraPermissionDenied: 'கேமரா அனுமதி மறுக்கப்பட்டது. கேமரா அணுகலை அனுமதிக்கவும் அல்லது பதிவேற்றத்தைப் பயன்படுத்தவும்.',
    cameraAccessError: 'கேமராவை அணுக முடியவில்லை. தயவுசெய்து பதிவேற்றத்தைப் பயன்படுத்தவும்.',
    addPhotoDefault: 'புகைப்படம் சேர்', addBorrowerPhoto: 'கடன் வாங்குபவரின் புகைப்படத்தைச் சேர் (பதிவேற்றம் அல்லது கேமரா)', addPhotoUploadCamera: 'புகைப்படம் சேர் (பதிவேற்றம் அல்லது கேமரா)',

    selectBorrower: 'கடன் வாங்குபவரைத் தேர்ந்தெடு', noActiveLoans: 'செயலில் கடன்கள் இல்லை. முதலில் உறுப்பினர்களைச் சேர்க்கவும்.',
    searchNameLocation: 'பெயர் அல்லது இடத்தைத் தேடு...', noMembersMatch: 'உங்கள் தேடலுக்கு பொருந்தும் உறுப்பினர் இல்லை.',
    capturePayment: 'பணம் பதிவு செய்', statusColon: 'நிலை:', recoveryProgress: 'மீட்பு முன்னேற்றம்',
    principalAmount: 'அசல் தொகை', totalDueLabel: 'மொத்த நிலுவை', recovered: 'மீட்கப்பட்டது',
    outstandingBalance: 'நிலுவைத் தொகை', paymentDetails: 'பணம் செலுத்தும் விவரங்கள்', cashFlow: 'ரொக்கம்', upiGpay: 'UPI / GPay',
    processing: 'செயலாக்கப்படுகிறது...', record: 'பதிவு செய்', payment: 'பணம்',

    ledgerBook: 'கணக்கு புத்தகம்', settled: 'தீர்க்கப்பட்டது', principalColon: 'அசல்:', paidColon: 'செலுத்தியது:',
    noLedgerEntries: 'இன்னும் கணக்குப் பதிவுகள் இல்லை',

    paymentRecorded: 'பணம் பதிவு செய்யப்பட்டது!', savedSuccessfully: 'வெற்றிகரமாக சேமிக்கப்பட்டது', remainingBalance: 'மீதமுள்ள தொகை',
    loanFullyPaid: 'கடன் முழுவதும் செலுத்தப்பட்டது!', sendWhatsappNotifications: 'வாட்ஸ்அப் அறிவிப்புகளை அனுப்பு',
    notifyAdminWhatsapp: 'வாட்ஸ்அப்பில் நிர்வாகிக்கு அறிவி', confirmToBorrower: 'கடன் வாங்குபவருக்கு உறுதிப்படுத்து', messagePreview: 'செய்தி முன்னோட்டம்',
    recordAnotherPayment: 'மற்றொரு பணம் செலுத்துதலைப் பதிவு செய்', collectPaymentTitle: 'பணம் வசூலி', asRole: 'ஆக', sort: 'வரிசைப்படுத்து',
    noActiveLoansFound: 'செயலில் கடன்கள் எதுவும் இல்லை.', noBorrowersMatch: 'உங்கள் தேடலுக்கு பொருந்தும் கடன் வாங்குபவர் இல்லை.', balance: 'இருப்பு',
    collectorYou: 'கலெக்டர் (நீங்கள்)', notesOptional: 'குறிப்புகள் (விருப்பம்)', saving: 'சேமிக்கப்படுகிறது...', cash: 'ரொக்கம்', gpayUpi: 'GPay / UPI',
    noPhone: 'தொலைபேசி இல்லை', dueColon: 'நிலுவை:', callBorrower: 'கடன் வாங்குபவரை அழை', call: 'அழை', paymentEntry: 'பணம் செலுத்தும் பதிவு',

    myCollections: 'எனது வசூல்கள்', allPaymentsRecorded: 'நீங்கள் பதிவு செய்த அனைத்து பணம் செலுத்துதல்களும்', entriesLabel: 'பதிவுகள்',
    noCollectionsYet: 'இன்னும் வசூல்கள் பதிவு செய்யப்படவில்லை. வசூலிக்கத் தொடங்குங்கள்!', loadingHistory: 'உங்கள் வசூல் வரலாறு ஏற்றப்படுகிறது...',

    newBorrowerLoan: 'புதிய கடன் வாங்குபவர் + கடன்', requiredNote: '* = அவசியம்', personalDetails: 'தனிப்பட்ட விவரங்கள்',
    fullName: 'முழுப்பெயர் *', shopBusinessName: 'கடை / வணிகப் பெயர்', primaryMobile: 'முதன்மை மொபைல் *',
    alternateMobile: 'மாற்று மொபைல்', areaInCoimbatore: 'கோயம்புத்தூர் பகுதி *', verifyPhoneOtp: 'OTP மூலம் தொலைபேசியை சரிபார் (விருப்பம்)',
    phoneVerified: 'தொலைபேசி சரிபார்க்கப்பட்டது', email: 'மின்னஞ்சல்', aadhaarNumber: 'ஆதார் எண்', address: 'முகவரி',
    guarantorDetails: 'உத்தரவாதி விவரங்கள்', guarantorName: 'உத்தரவாதி பெயர்', guarantorPhone: 'உத்தரவாதி தொலைபேசி',
    guarantorAddress: 'உத்தரவாதி முகவரி', loanDetails: 'கடன் விவரங்கள்', loanAmount: 'கடன் தொகை (₹) *',
    charges: 'கட்டணங்கள் (%)', chargesAmount: 'கட்டணத் தொகை (₹)', auto: 'தானாக', startDate: 'தொடக்க தேதி *', dueDate: 'செலுத்த வேண்டிய தேதி *',
    chargesAndFees: 'கட்டணங்கள் மற்றும் கட்டணங்கள் (₹)', autoSplitNote: 'கட்டணங்களிலிருந்து தானாகப் பிரிக்கப்பட்டது — வட்டி 18%, கள சரிபார்ப்பு 31%, ஆவண கட்டணம் 30%, செயலாக்க கட்டணம் 21%. இந்த கடனுக்கு வேறு தொகைகள் தேவைப்பட்டால் கீழே சரிசெய்யவும்.',
    fieldVerification: 'கள சரிபார்ப்பு', documentFee: 'ஆவண கட்டணம்', processingFee: 'செயலாக்க கட்டணம்',
    breakdown: 'விவரப்பிரிவு', principalLoanAmount: 'அசல் (கடன் தொகை)', ofWhich: 'இதில்',
    deductedUpfront: 'அசலிலிருந்து முன்கூட்டியே கழிக்கப்பட்டது', cashDisbursedToBorrower: 'கடன் வாங்குபவருக்கு வழங்கப்பட்ட ரொக்கம்',
    totalDueRepayable: 'மொத்த நிலுவை (திருப்பிச் செலுத்த வேண்டியது)', repaymentSchedule: 'திருப்பிச் செலுத்தும் அட்டவணை', amountPerInstallment: 'ஒரு தவணைக்கான தொகை (₹)',
    disbursementSmsLanguage: 'கடன் வழங்கல் SMS மொழி', autoWhatsappReminders: 'தானியங்கி வாட்ஸ்அப் நினைவூட்டல்கள்',
    confirmLoanDisbursal: 'கடன் வழங்கலை உறுதிப்படுத்து', creating: 'உருவாக்கப்படுகிறது...',
    existingBorrower: 'ஏற்கனவே உள்ள கடன் வாங்குபவர்', newBorrower: 'புதிய கடன் வாங்குபவர்', selectZone: 'பகுதியைத் தேர்ந்தெடு…',
    mergeBorrowers: 'கடன் வாங்குபவர்களை இணை', merge: 'இணை', mergeSelected: 'தேர்ந்தெடுக்கப்பட்டவர்களை இணை',
    noBorrowersYet: 'இன்னும் கடன் வாங்குபவர்கள் இல்லை. சேர்க்க + ஐ தட்டவும்.', highestBalance: 'அதிக இருப்பு', nameAZ: 'பெயர் A-Z',
    byArea: 'கோயம்புத்தூர் பகுதி வாரியாக', newestFirst: 'புதியது முதலில்', due: 'நிலுவை', paidSuffix: 'செலுத்தப்பட்டது',
    loanDisbursed: 'கடன் வழங்கப்பட்டது!', borrowerAccountNumber: 'கடன் வாங்குபவர் கணக்கு எண்', done: 'முடிந்தது',
    noPhoneSmsUnavailable: 'தொலைபேசி எண் இல்லை — SMS சாத்தியமில்லை.',
    freqCustom: 'விருப்பம்', freqDailyDesc: 'தினமும் வசூலிக்கப்படும்', freqWeeklyDesc: 'வாரத்திற்கு ஒருமுறை',
    freqMonthlyDesc: 'மாதத்திற்கு ஒருமுறை', freqCustomDesc: 'உங்கள் சொந்த தொகையை அமைக்கவும்',
    otpSending: 'அனுப்பப்படுகிறது…', sendOtpToVerifyPhone: 'தொலைபேசியை சரிபார்க்க OTP அனுப்பு', testOtpLabel: 'சோதனை OTP:',
    otpVerifying: 'சரிபார்க்கப்படுகிறது…', verifyOtpBtn: 'OTP ஐ சரிபார்',
    mergeBorrowersDesc: 'இணைக்க சரியாக 2 கடன் வாங்குபவர்களைத் தேர்ந்தெடுக்கவும். அவர்களின் கடன் பதிவுகள் முதலில் தேர்ந்தெடுக்கப்பட்டவருடன் இணைக்கப்படும்.',
    outstandingColon: 'நிலுவை:', disbursedTo: 'க்கு வழங்கப்பட்டது', disbursementSms: 'கடன் வழங்கல் SMS',
    sendSmsToBorrower: 'கடன் வாங்குபவருக்கு SMS அனுப்பு',
  },
  te: {
    appName: 'వసూల్‌ప్రో', appTagline: 'మైక్రో ఫైనాన్స్ సిస్టమ్',
    navMain: 'ప్రధాన', navFinance: 'ఆర్థిక', navSystem: 'సిస్టమ్', navCollector: 'కలెక్టర్',
    dashboard: 'డాష్‌బోర్డ్', borrowers: 'రుణగ్రహీతలు', collection: 'వసూలు', ledger: 'లెడ్జర్',
    expenses: 'ఖర్చులు', reports: 'నివేదికలు', staff: 'సిబ్బంది', settings: 'సెట్టింగ్‌లు',
    collectPayment: 'చెల్లింపు వసూలు చేయండి', history: 'చరిత్ర', profile: 'ప్రొఫైల్', transactions: 'లావాదేవీలు',
    home: 'హోమ్', collect: 'వసూలు', more: 'మరిన్ని', logout: 'లాగ్ అవుట్', language: 'భాష',
    notifications: 'ప్రకటనలు', today: 'ఈరోజు', settingsComingSoon: 'సెట్టింగ్‌లు త్వరలో వస్తాయి',
    welcomeBack: 'కి తిరిగి స్వాగతం', helloGreeting: 'నమస్కారం', searchBorrowers: 'రుణగ్రహీతలను వెతకండి...',
    collectedToday: 'ఈరోజు వసూలు', newLoan: 'కొత్త రుణం', addBorrower: 'రుణగ్రహీతను జోడించండి',
    todaysCollection: 'ఈరోజు వసూలు', activeBorrowers: 'క్రియాశీల రుణగ్రహీతలు',
    totalOutstanding: 'మొత్తం బకాయి', totalCollected: 'మొత్తం వసూలు',
    dueToday: 'ఈరోజు చెల్లించవలసినది', overdueAlerts: 'గడువు మీరిన హెచ్చరికలు', seeAll: 'అన్నీ చూడండి',
    borrowersAndLoans: 'రుణగ్రహీతలు మరియు రుణాలు', allAreas: 'అన్ని ప్రాంతాలు',
    welcome: 'స్వాగతం!', howLogin: 'మీరు ఎలా లాగిన్ కావాలనుకుంటున్నారు?',
    imAdmin: 'నేను అడ్మిన్', imCollector: 'నేను కలెక్టర్',
    sendOtp: 'OTP పంపండి', verifySignIn: 'ధృవీకరించి సైన్ ఇన్ చేయండి', enterOtp: 'OTP నమోదు చేయండి', back: 'వెనుకకు',

    ledgerPageTitle: 'వసూలు లెడ్జర్', entriesSuffix: 'నమోదులు', allStaff: 'అందరు సిబ్బంది', recordPayment: 'చెల్లింపును నమోదు చేయండి',
    amountReceived: 'అందుకున్న మొత్తం (₹)', penaltyLateFee: 'జరిమానా / ఆలస్య రుసుము (₹)', confirmPayment: 'చెల్లింపును నిర్ధారించండి',
    totalDueToday: 'ఈరోజు మొత్తం చెల్లించవలసినది', collectedLabel: 'వసూలైంది', pendingLabel: 'పెండింగ్', collectionPercent: 'వసూలు %',
    collectionProgress: 'వసూలు పురోగతి', daily: 'రోజువారీ', weekly: 'వారానికొకసారి', monthly: 'నెలవారీ', allDue: 'అన్ని బాకీలు',
    tableBorrower: 'రుణగ్రహీత', tablePhone: 'ఫోన్', tableType: 'రకం', tableDueAmount: 'బాకీ మొత్తం', tablePaid: 'చెల్లించినది',
    tableStatus: 'స్థితి', tableStaff: 'సిబ్బంది', tableAction: 'చర్య', noInstallmentsDue: 'ఈ ఫిల్టర్‌కు వాయిదాలు లేవు',
    statusPaid: 'చెల్లించారు', statusPartial: 'పాక్షికం', statusPending: 'పెండింగ్', statusOverdue: 'గడువు మీరినది',
    modeFull: 'పూర్తి', modePartial: 'పాక్షిక', modeAdvance: 'అడ్వాన్స్',

    expensesAndCapital: 'ఖర్చులు & మూలధనం', businessFinancialHealth: 'వ్యాపార ఆర్థిక పరిస్థితి యొక్క అవలోకనం',
    logInvestment: 'పెట్టుబడిని నమోదు చేయండి', addExpense: 'ఖర్చును జోడించండి', totalInvested: 'మొత్తం పెట్టుబడి', totalExpenses: 'మొత్తం ఖర్చులు',
    capitalInvestments: 'మూలధన పెట్టుబడులు', logExpense: 'ఖర్చును నమోదు చేయండి', category: 'వర్గం', amountRs: 'మొత్తం (₹)',
    dateLabel: 'తేదీ', descriptionLabel: 'వివరణ', logCapitalInvestment: 'మూలధన పెట్టుబడిని నమోదు చేయండి',
    amountInvested: 'పెట్టుబడి పెట్టిన మొత్తం (₹)', noteLabel: 'గమనిక',

    financialReports: 'ఆర్థిక నివేదికలు', analyticsExportCenter: 'విశ్లేషణ మరియు ఎగుమతి కేంద్రం', excel: 'ఎక్సెల్', pdfReport: 'PDF నివేదిక',
    reportPL: 'లాభ నష్టం', reportPLDesc: 'ఆదాయం మరియు ఖర్చులు', reportCollection: 'వసూలు సారాంశం',
    reportCollectionDesc: 'రోజువారీ వసూలు పనితీరు', reportPortfolio: 'రుణ పోర్ట్‌ఫోలియో',
    reportPortfolioDesc: 'రకం మరియు స్థితి ప్రకారం క్రియాశీల రుణాలు', reportOverdue: 'గడువు మీరిన నివేదిక',
    reportOverdueDesc: 'అన్ని గడువు మీరిన ఖాతాలు మరియు వ్యవధి', grossRevenue: 'స్థూల ఆదాయం',
    grossRevenueNote: 'మొత్తం వడ్డీ + అసలు వసూలు చేయబడింది', totalExpensesNote: 'జీతాలు, ఇంధనం, కార్యాలయం, ఇతరాలు',
    outstandingLabel: 'బకాయి', outstandingNote: 'వసూలు చేయవలసిన పెండింగ్ మొత్తం', tableDay: 'రోజు', tableTarget: 'లక్ష్యం',
    tableAchievement: 'సాధన', tablePrincipal: 'అసలు', tableTotalDue: 'మొత్తం బాకీ', statusActive: 'క్రియాశీలం',
    statusClosed: 'మూసివేయబడింది', statusDefaulted: 'డిఫాల్ట్', loansSuffix: 'రుణాలు', noOverdueAccounts: 'గడువు మీరిన ఖాతాలు లేవు!',
    tableDueDate: 'గడువు తేదీ', tableAmountDue: 'బాకీ మొత్తం', tableDaysOverdue: 'ఆలస్యమైన రోజులు', daysSuffix: 'రోజులు',

    staffManagement: 'సిబ్బంది నిర్వహణ', teamMembers: 'బృంద సభ్యులు', rbacEnabled: 'RBAC ప్రారంభించబడింది', addStaff: 'సిబ్బందిని జోడించండి',
    addStaffMember: 'సిబ్బంది సభ్యుడిని జోడించండి', fullNameRequired: 'పూర్తి పేరు *', role: 'పాత్ర', roleAdmin: 'అడ్మిన్', roleManager: 'మేనేజర్',
    roleCollector: 'కలెక్టర్', phone: 'ఫోన్', monthlyTarget: 'నెలవారీ లక్ష్యం (₹)', efficiency: 'సామర్థ్యం', target: 'లక్ష్యం',
    loans: 'రుణాలు', rolePermissionMatrix: 'పాత్ర అనుమతి మ్యాట్రిక్స్', permission: 'అనుమతి', permViewDashboard: 'డాష్‌బోర్డ్ చూడండి',
    permCreateLoans: 'రుణాలు సృష్టించండి', permCollectPayments: 'చెల్లింపులు వసూలు చేయండి', permViewReports: 'నివేదికలు & లాభనష్టాలు చూడండి',
    permManageStaff: 'సిబ్బందిని నిర్వహించండి', permDeleteRecords: 'రికార్డులను తొలగించండి', permExportData: 'డేటాను ఎగుమతి చేయండి',
    permViewCapital: 'మూలధనం/పెట్టుబడి చూడండి', recentAuditLog: 'ఇటీవలి ఆడిట్ లాగ్',

    myProfile: 'నా ప్రొఫైల్', verified: 'ధృవీకరించబడింది', contactInformation: 'సంప్రదింపు సమాచారం', emailAddress: 'ఇమెయిల్ చిరునామా',
    phoneNumber: 'ఫోన్ నంబర్', homeAddress: 'ఇంటి చిరునామా', financeAndProofs: 'ఆర్థిక & ఆధారాలు',
    linkedBankAccount: 'లింక్ చేయబడిన బ్యాంక్ ఖాతా', mandatoryProofKyc: 'తప్పనిసరి ఆధార కాపీ (KYC)', notYetUploaded: 'ఇంకా అప్‌లోడ్ చేయలేదు',
    upload: 'అప్‌లోడ్ చేయండి', loginHistory: 'లాగిన్ చరిత్ర', signOutSafely: 'సురక్షితంగా సైన్ అవుట్ చేయండి', loadingProfile: 'ప్రొఫైల్ లోడ్ అవుతోంది...',

    uploadBtn: 'అప్‌లోడ్ చేయండి', cameraBtn: 'కెమెరా', removeBtn: 'తొలగించండి', takePhoto: 'ఫోటో తీయండి', retake: 'మళ్ళీ తీయండి',
    usePhoto: 'ఫోటోను ఉపయోగించండి', flip: 'తిప్పండి', capture: 'క్యాప్చర్ చేయండి',
    cameraNotSupported: 'ఈ పరికరం/బ్రౌజర్‌లో కెమెరా మద్దతు లేదు. దయచేసి అప్‌లోడ్ ఉపయోగించండి.',
    cameraPermissionDenied: 'కెమెరా అనుమతి తిరస్కరించబడింది. కెమెరా యాక్సెస్ ఇవ్వండి లేదా అప్‌లోడ్ ఉపయోగించండి.',
    cameraAccessError: 'కెమెరాను యాక్సెస్ చేయలేకపోయాము. దయచేసి అప్‌లోడ్ ఉపయోగించండి.',
    addPhotoDefault: 'ఫోటో జోడించండి', addBorrowerPhoto: 'రుణగ్రహీత ఫోటోను జోడించండి (అప్‌లోడ్ లేదా కెమెరా)', addPhotoUploadCamera: 'ఫోటో జోడించండి (అప్‌లోడ్ లేదా కెమెరా)',

    selectBorrower: 'రుణగ్రహీతను ఎంచుకోండి', noActiveLoans: 'క్రియాశీల రుణాలు లేవు. ముందుగా సభ్యులను జోడించండి.',
    searchNameLocation: 'పేరు లేదా స్థానం వెతకండి...', noMembersMatch: 'మీ శోధనకు సరిపోలే సభ్యులు లేరు.',
    capturePayment: 'చెల్లింపును నమోదు చేయండి', statusColon: 'స్థితి:', recoveryProgress: 'రికవరీ పురోగతి',
    principalAmount: 'అసలు మొత్తం', totalDueLabel: 'మొత్తం బాకీ', recovered: 'రికవరీ చేయబడింది',
    outstandingBalance: 'బకాయి నిల్వ', paymentDetails: 'చెల్లింపు వివరాలు', cashFlow: 'నగదు ప్రవాహం', upiGpay: 'UPI / GPay',
    processing: 'ప్రాసెస్ అవుతోంది...', record: 'నమోదు చేయండి', payment: 'చెల్లింపు',

    ledgerBook: 'లెడ్జర్ పుస్తకం', settled: 'పరిష్కరించబడింది', principalColon: 'అసలు:', paidColon: 'చెల్లించినది:',
    noLedgerEntries: 'ఇంకా లెడ్జర్ నమోదులు లేవు',

    paymentRecorded: 'చెల్లింపు నమోదైంది!', savedSuccessfully: 'విజయవంతంగా సేవ్ చేయబడింది', remainingBalance: 'మిగిలిన నిల్వ',
    loanFullyPaid: 'రుణం పూర్తిగా చెల్లించబడింది!', sendWhatsappNotifications: 'వాట్సాప్ నోటిఫికేషన్‌లు పంపండి',
    notifyAdminWhatsapp: 'వాట్సాప్‌లో అడ్మిన్‌కు తెలియజేయండి', confirmToBorrower: 'రుణగ్రహీతకు నిర్ధారించండి', messagePreview: 'సందేశ ప్రివ్యూ',
    recordAnotherPayment: 'మరొక చెల్లింపును నమోదు చేయండి', collectPaymentTitle: 'చెల్లింపు వసూలు చేయండి', asRole: 'గా', sort: 'క్రమబద్ధీకరించండి',
    noActiveLoansFound: 'క్రియాశీల రుణాలు కనుగొనబడలేదు.', noBorrowersMatch: 'మీ శోధనకు సరిపోలే రుణగ్రహీతలు లేరు.', balance: 'నిల్వ',
    collectorYou: 'కలెక్టర్ (మీరు)', notesOptional: 'గమనికలు (ఐచ్ఛికం)', saving: 'సేవ్ అవుతోంది...', cash: 'నగదు', gpayUpi: 'GPay / UPI',
    noPhone: 'ఫోన్ లేదు', dueColon: 'బాకీ:', callBorrower: 'రుణగ్రహీతకు కాల్ చేయండి', call: 'కాల్', paymentEntry: 'చెల్లింపు నమోదు',

    myCollections: 'నా వసూళ్లు', allPaymentsRecorded: 'మీరు నమోదు చేసిన అన్ని చెల్లింపులు', entriesLabel: 'నమోదులు',
    noCollectionsYet: 'ఇంకా వసూళ్లు నమోదు కాలేదు. వసూలు చేయడం ప్రారంభించండి!', loadingHistory: 'మీ వసూలు చరిత్ర లోడ్ అవుతోంది...',

    newBorrowerLoan: 'కొత్త రుణగ్రహీత + రుణం', requiredNote: '* = తప్పనిసరి', personalDetails: 'వ్యక్తిగత వివరాలు',
    fullName: 'పూర్తి పేరు *', shopBusinessName: 'దుకాణం / వ్యాపార పేరు', primaryMobile: 'ప్రాథమిక మొబైల్ *',
    alternateMobile: 'ప్రత్యామ్నాయ మొబైల్', areaInCoimbatore: 'కోయంబత్తూర్‌లో ప్రాంతం *', verifyPhoneOtp: 'OTPతో ఫోన్ ధృవీకరించండి (ఐచ్ఛికం)',
    phoneVerified: 'ఫోన్ ధృవీకరించబడింది', email: 'ఇమెయిల్', aadhaarNumber: 'ఆధార్ నంబర్', address: 'చిరునామా',
    guarantorDetails: 'హామీదారు వివరాలు', guarantorName: 'హామీదారు పేరు', guarantorPhone: 'హామీదారు ఫోన్',
    guarantorAddress: 'హామీదారు చిరునామా', loanDetails: 'రుణ వివరాలు', loanAmount: 'రుణ మొత్తం (₹) *',
    charges: 'ఛార్జీలు (%)', chargesAmount: 'ఛార్జీల మొత్తం (₹)', auto: 'స్వయంచాలకంగా', startDate: 'ప్రారంభ తేదీ *', dueDate: 'గడువు తేదీ *',
    chargesAndFees: 'ఛార్జీలు & రుసుములు (₹)', autoSplitNote: 'ఛార్జీల నుండి స్వయంచాలకంగా విభజించబడింది — వడ్డీ 18%, ఫీల్డ్ వెరిఫికేషన్ 31%, డాక్యుమెంట్ ఫీజు 30%, ప్రాసెసింగ్ ఫీజు 21%. ఈ రుణానికి వేరే మొత్తాలు అవసరమైతే క్రింద సర్దుబాటు చేయండి.',
    fieldVerification: 'ఫీల్డ్ వెరిఫికేషన్', documentFee: 'డాక్యుమెంట్ ఫీజు', processingFee: 'ప్రాసెసింగ్ ఫీజు',
    breakdown: 'విభజన', principalLoanAmount: 'అసలు (రుణ మొత్తం)', ofWhich: 'ఇందులో',
    deductedUpfront: 'అసలు నుండి ముందుగానే తీసివేయబడింది', cashDisbursedToBorrower: 'రుణగ్రహీతకు ఇచ్చిన నగదు',
    totalDueRepayable: 'మొత్తం బాకీ (చెల్లించవలసినది)', repaymentSchedule: 'చెల్లింపు షెడ్యూల్', amountPerInstallment: 'ఒక్కో వాయిదా మొత్తం (₹)',
    disbursementSmsLanguage: 'పంపిణీ SMS భాష', autoWhatsappReminders: 'ఆటో వాట్సాప్ రిమైండర్‌లు',
    confirmLoanDisbursal: 'రుణ పంపిణీని నిర్ధారించండి', creating: 'సృష్టించబడుతోంది...',
    existingBorrower: 'ఇప్పటికే ఉన్న రుణగ్రహీత', newBorrower: 'కొత్త రుణగ్రహీత', selectZone: 'ప్రాంతాన్ని ఎంచుకోండి…',
    mergeBorrowers: 'రుణగ్రహీతలను విలీనం చేయండి', merge: 'విలీనం చేయండి', mergeSelected: 'ఎంచుకున్నవారిని విలీనం చేయండి',
    noBorrowersYet: 'ఇంకా రుణగ్రహీతలు లేరు. జోడించడానికి + నొక్కండి.', highestBalance: 'అత్యధిక నిల్వ', nameAZ: 'పేరు A-Z',
    byArea: 'కోయంబత్తూర్ ప్రాంతం వారీగా', newestFirst: 'తాజాది మొదట', due: 'బాకీ', paidSuffix: 'చెల్లించారు',
    loanDisbursed: 'రుణం పంపిణీ చేయబడింది!', borrowerAccountNumber: 'రుణగ్రహీత ఖాతా సంఖ్య', done: 'పూర్తయింది',
    noPhoneSmsUnavailable: 'ఫోన్ నంబర్ లేదు — SMS అందుబాటులో లేదు.',
    freqCustom: 'కస్టమ్', freqDailyDesc: 'ప్రతిరోజూ వసూలు చేయబడుతుంది', freqWeeklyDesc: 'వారానికి ఒకసారి',
    freqMonthlyDesc: 'నెలకు ఒకసారి', freqCustomDesc: 'మీ స్వంత మొత్తాన్ని సెట్ చేయండి',
    otpSending: 'పంపుతోంది…', sendOtpToVerifyPhone: 'ఫోన్ ధృవీకరించడానికి OTP పంపండి', testOtpLabel: 'టెస్ట్ OTP:',
    otpVerifying: 'ధృవీకరిస్తోంది…', verifyOtpBtn: 'OTP ధృవీకరించండి',
    mergeBorrowersDesc: 'విలీనం చేయడానికి సరిగ్గా 2 రుణగ్రహీతలను ఎంచుకోండి. వారి రుణ రికార్డులు మొదట ఎంచుకున్న దానితో కలుపబడతాయి.',
    outstandingColon: 'బకాయి:', disbursedTo: 'కి పంపిణీ చేయబడింది', disbursementSms: 'పంపిణీ SMS',
    sendSmsToBorrower: 'రుణగ్రహీతకు SMS పంపండి',
  },
  kn: {
    appName: 'ವಸೂಲ್‌ಪ್ರೊ', appTagline: 'ಮೈಕ್ರೋ ಫೈನಾನ್ಸ್ ಸಿಸ್ಟಮ್',
    navMain: 'ಮುಖ್ಯ', navFinance: 'ಹಣಕಾಸು', navSystem: 'ಸಿಸ್ಟಮ್', navCollector: 'ಕಲೆಕ್ಟರ್',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', borrowers: 'ಸಾಲಗಾರರು', collection: 'ವಸೂಲಿ', ledger: 'ಲೆಡ್ಜರ್',
    expenses: 'ಖರ್ಚುಗಳು', reports: 'ವರದಿಗಳು', staff: 'ಸಿಬ್ಬಂದಿ', settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    collectPayment: 'ಪಾವತಿ ಸಂಗ್ರಹಿಸಿ', history: 'ಇತಿಹಾಸ', profile: 'ಪ್ರೊಫೈಲ್', transactions: 'ವಹಿವಾಟುಗಳು',
    home: 'ಮುಖಪುಟ', collect: 'ಸಂಗ್ರಹ', more: 'ಇನ್ನಷ್ಟು', logout: 'ಲಾಗ್ಔಟ್', language: 'ಭಾಷೆ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು', today: 'ಇಂದು', settingsComingSoon: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ',
    welcomeBack: 'ಗೆ ಮತ್ತೆ ಸ್ವಾಗತ', helloGreeting: 'ನಮಸ್ಕಾರ', searchBorrowers: 'ಸಾಲಗಾರರನ್ನು ಹುಡುಕಿ...',
    collectedToday: 'ಇಂದು ಸಂಗ್ರಹಿಸಿದ್ದು', newLoan: 'ಹೊಸ ಸಾಲ', addBorrower: 'ಸಾಲಗಾರರನ್ನು ಸೇರಿಸಿ',
    todaysCollection: 'ಇಂದಿನ ಸಂಗ್ರಹ', activeBorrowers: 'ಸಕ್ರಿಯ ಸಾಲಗಾರರು',
    totalOutstanding: 'ಒಟ್ಟು ಬಾಕಿ', totalCollected: 'ಒಟ್ಟು ಸಂಗ್ರಹ',
    dueToday: 'ಇಂದು ಬಾಕಿ', overdueAlerts: 'ವಿಳಂಬ ಎಚ್ಚರಿಕೆಗಳು', seeAll: 'ಎಲ್ಲಾ ನೋಡಿ',
    borrowersAndLoans: 'ಸಾಲಗಾರರು ಮತ್ತು ಸಾಲಗಳು', allAreas: 'ಎಲ್ಲಾ ಪ್ರದೇಶಗಳು',
    welcome: 'ಸ್ವಾಗತ!', howLogin: 'ನೀವು ಹೇಗೆ ಲಾಗಿನ್ ಆಗಲು ಬಯಸುತ್ತೀರಿ?',
    imAdmin: 'ನಾನು ಅಡ್ಮಿನ್', imCollector: 'ನಾನು ಕಲೆಕ್ಟರ್',
    sendOtp: 'OTP ಕಳುಹಿಸಿ', verifySignIn: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸೈನ್ ಇನ್ ಮಾಡಿ', enterOtp: 'OTP ನಮೂದಿಸಿ', back: 'ಹಿಂದೆ',

    ledgerPageTitle: 'ವಸೂಲಿ ಲೆಡ್ಜರ್', entriesSuffix: 'ನಮೂದುಗಳು', allStaff: 'ಎಲ್ಲಾ ಸಿಬ್ಬಂದಿ', recordPayment: 'ಪಾವತಿ ದಾಖಲಿಸಿ',
    amountReceived: 'ಸ್ವೀಕರಿಸಿದ ಮೊತ್ತ (₹)', penaltyLateFee: 'ದಂಡ / ವಿಳಂಬ ಶುಲ್ಕ (₹)', confirmPayment: 'ಪಾವತಿಯನ್ನು ದೃಢೀಕರಿಸಿ',
    totalDueToday: 'ಇಂದು ಒಟ್ಟು ಬಾಕಿ', collectedLabel: 'ಸಂಗ್ರಹಿಸಲಾಗಿದೆ', pendingLabel: 'ಬಾಕಿ', collectionPercent: 'ಸಂಗ್ರಹ %',
    collectionProgress: 'ಸಂಗ್ರಹ ಪ್ರಗತಿ', daily: 'ದೈನಂದಿನ', weekly: 'ಸಾಪ್ತಾಹಿಕ', monthly: 'ಮಾಸಿಕ', allDue: 'ಎಲ್ಲಾ ಬಾಕಿ',
    tableBorrower: 'ಸಾಲಗಾರ', tablePhone: 'ಫೋನ್', tableType: 'ಪ್ರಕಾರ', tableDueAmount: 'ಬಾಕಿ ಮೊತ್ತ', tablePaid: 'ಪಾವತಿಸಿದ್ದು',
    tableStatus: 'ಸ್ಥಿತಿ', tableStaff: 'ಸಿಬ್ಬಂದಿ', tableAction: 'ಕ್ರಮ', noInstallmentsDue: 'ಈ ಫಿಲ್ಟರ್‌ಗೆ ಯಾವುದೇ ಕಂತುಗಳು ಬಾಕಿ ಇಲ್ಲ',
    statusPaid: 'ಪಾವತಿಸಲಾಗಿದೆ', statusPartial: 'ಭಾಗಶಃ', statusPending: 'ಬಾಕಿ', statusOverdue: 'ವಿಳಂಬ',
    modeFull: 'ಪೂರ್ಣ', modePartial: 'ಭಾಗಶಃ', modeAdvance: 'ಮುಂಗಡ',

    expensesAndCapital: 'ಖರ್ಚುಗಳು ಮತ್ತು ಬಂಡವಾಳ', businessFinancialHealth: 'ವ್ಯಾಪಾರ ಆರ್ಥಿಕ ಆರೋಗ್ಯದ ಅವಲೋಕನ',
    logInvestment: 'ಹೂಡಿಕೆಯನ್ನು ದಾಖಲಿಸಿ', addExpense: 'ಖರ್ಚು ಸೇರಿಸಿ', totalInvested: 'ಒಟ್ಟು ಹೂಡಿಕೆ', totalExpenses: 'ಒಟ್ಟು ಖರ್ಚುಗಳು',
    capitalInvestments: 'ಬಂಡವಾಳ ಹೂಡಿಕೆಗಳು', logExpense: 'ಖರ್ಚನ್ನು ದಾಖಲಿಸಿ', category: 'ವರ್ಗ', amountRs: 'ಮೊತ್ತ (₹)',
    dateLabel: 'ದಿನಾಂಕ', descriptionLabel: 'ವಿವರಣೆ', logCapitalInvestment: 'ಬಂಡವಾಳ ಹೂಡಿಕೆಯನ್ನು ದಾಖಲಿಸಿ',
    amountInvested: 'ಹೂಡಿಕೆ ಮಾಡಿದ ಮೊತ್ತ (₹)', noteLabel: 'ಟಿಪ್ಪಣಿ',

    financialReports: 'ಹಣಕಾಸು ವರದಿಗಳು', analyticsExportCenter: 'ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ರಫ್ತು ಕೇಂದ್ರ', excel: 'ಎಕ್ಸೆಲ್', pdfReport: 'PDF ವರದಿ',
    reportPL: 'ಲಾಭ ನಷ್ಟ', reportPLDesc: 'ಆದಾಯ ಮತ್ತು ಖರ್ಚುಗಳು', reportCollection: 'ಸಂಗ್ರಹ ಸಾರಾಂಶ',
    reportCollectionDesc: 'ದಿನವಾರು ಸಂಗ್ರಹ ಸಾಧನೆ', reportPortfolio: 'ಸಾಲ ಬಂಡವಾಳ',
    reportPortfolioDesc: 'ಪ್ರಕಾರ ಮತ್ತು ಸ್ಥಿತಿಯ ಪ್ರಕಾರ ಸಕ್ರಿಯ ಸಾಲಗಳು', reportOverdue: 'ವಿಳಂಬ ವರದಿ',
    reportOverdueDesc: 'ಎಲ್ಲಾ ವಿಳಂಬ ಖಾತೆಗಳು ಮತ್ತು ಅವಧಿ', grossRevenue: 'ಒಟ್ಟು ಆದಾಯ',
    grossRevenueNote: 'ಒಟ್ಟು ಬಡ್ಡಿ + ಅಸಲು ಸಂಗ್ರಹಿಸಲಾಗಿದೆ', totalExpensesNote: 'ಸಂಬಳ, ಇಂಧನ, ಕಚೇರಿ, ಇತರೆ',
    outstandingLabel: 'ಬಾಕಿ', outstandingNote: 'ಮರುಪಡೆಯಬೇಕಾದ ಬಾಕಿ ಮೊತ್ತ', tableDay: 'ದಿನ', tableTarget: 'ಗುರಿ',
    tableAchievement: 'ಸಾಧನೆ', tablePrincipal: 'ಅಸಲು', tableTotalDue: 'ಒಟ್ಟು ಬಾಕಿ', statusActive: 'ಸಕ್ರಿಯ',
    statusClosed: 'ಮುಚ್ಚಲಾಗಿದೆ', statusDefaulted: 'ಡಿಫಾಲ್ಟ್', loansSuffix: 'ಸಾಲಗಳು', noOverdueAccounts: 'ವಿಳಂಬ ಖಾತೆಗಳಿಲ್ಲ!',
    tableDueDate: 'ಬಾಕಿ ದಿನಾಂಕ', tableAmountDue: 'ಬಾಕಿ ಮೊತ್ತ', tableDaysOverdue: 'ವಿಳಂಬ ದಿನಗಳು', daysSuffix: 'ದಿನಗಳು',

    staffManagement: 'ಸಿಬ್ಬಂದಿ ನಿರ್ವಹಣೆ', teamMembers: 'ತಂಡದ ಸದಸ್ಯರು', rbacEnabled: 'RBAC ಸಕ್ರಿಯಗೊಂಡಿದೆ', addStaff: 'ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿ',
    addStaffMember: 'ಸಿಬ್ಬಂದಿ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ', fullNameRequired: 'ಪೂರ್ಣ ಹೆಸರು *', role: 'ಪಾತ್ರ', roleAdmin: 'ಅಡ್ಮಿನ್', roleManager: 'ಮ್ಯಾನೇಜರ್',
    roleCollector: 'ಕಲೆಕ್ಟರ್', phone: 'ಫೋನ್', monthlyTarget: 'ಮಾಸಿಕ ಗುರಿ (₹)', efficiency: 'ದಕ್ಷತೆ', target: 'ಗುರಿ',
    loans: 'ಸಾಲಗಳು', rolePermissionMatrix: 'ಪಾತ್ರ ಅನುಮತಿ ಮ್ಯಾಟ್ರಿಕ್ಸ್', permission: 'ಅನುಮತಿ', permViewDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ನೋಡಿ',
    permCreateLoans: 'ಸಾಲಗಳನ್ನು ರಚಿಸಿ', permCollectPayments: 'ಪಾವತಿಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ', permViewReports: 'ವರದಿಗಳು & ಲಾಭನಷ್ಟ ನೋಡಿ',
    permManageStaff: 'ಸಿಬ್ಬಂದಿ ನಿರ್ವಹಿಸಿ', permDeleteRecords: 'ದಾಖಲೆಗಳನ್ನು ಅಳಿಸಿ', permExportData: 'ಡೇಟಾ ರಫ್ತು ಮಾಡಿ',
    permViewCapital: 'ಬಂಡವಾಳ/ಹೂಡಿಕೆ ನೋಡಿ', recentAuditLog: 'ಇತ್ತೀಚಿನ ಆಡಿಟ್ ಲಾಗ್',

    myProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್', verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ', contactInformation: 'ಸಂಪರ್ಕ ಮಾಹಿತಿ', emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ', homeAddress: 'ಮನೆ ವಿಳಾಸ', financeAndProofs: 'ಹಣಕಾಸು & ಪುರಾವೆಗಳು',
    linkedBankAccount: 'ಲಿಂಕ್ ಮಾಡಿದ ಬ್ಯಾಂಕ್ ಖಾತೆ', mandatoryProofKyc: 'ಕಡ್ಡಾಯ ಪುರಾವೆ ಪ್ರತಿ (KYC)', notYetUploaded: 'ಇನ್ನೂ ಅಪ್‌ಲೋಡ್ ಆಗಿಲ್ಲ',
    upload: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', loginHistory: 'ಲಾಗಿನ್ ಇತಿಹಾಸ', signOutSafely: 'ಸುರಕ್ಷಿತವಾಗಿ ಸೈನ್ ಔಟ್ ಮಾಡಿ', loadingProfile: 'ಪ್ರೊಫೈಲ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',

    uploadBtn: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', cameraBtn: 'ಕ್ಯಾಮೆರಾ', removeBtn: 'ತೆಗೆದುಹಾಕಿ', takePhoto: 'ಫೋಟೋ ತೆಗೆಯಿರಿ', retake: 'ಮತ್ತೆ ತೆಗೆಯಿರಿ',
    usePhoto: 'ಫೋಟೋ ಬಳಸಿ', flip: 'ತಿರುಗಿಸಿ', capture: 'ಸೆರೆಹಿಡಿಯಿರಿ',
    cameraNotSupported: 'ಈ ಸಾಧನ/ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಕ್ಯಾಮೆರಾ ಬೆಂಬಲಿತವಿಲ್ಲ. ದಯವಿಟ್ಟು ಅಪ್‌ಲೋಡ್ ಬಳಸಿ.',
    cameraPermissionDenied: 'ಕ್ಯಾಮೆರಾ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ. ಕ್ಯಾಮೆರಾ ಪ್ರವೇಶ ನೀಡಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಬಳಸಿ.',
    cameraAccessError: 'ಕ್ಯಾಮೆರಾ ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಅಪ್‌ಲೋಡ್ ಬಳಸಿ.',
    addPhotoDefault: 'ಫೋಟೋ ಸೇರಿಸಿ', addBorrowerPhoto: 'ಸಾಲಗಾರರ ಫೋಟೋ ಸೇರಿಸಿ (ಅಪ್‌ಲೋಡ್ ಅಥವಾ ಕ್ಯಾಮೆರಾ)', addPhotoUploadCamera: 'ಫೋಟೋ ಸೇರಿಸಿ (ಅಪ್‌ಲೋಡ್ ಅಥವಾ ಕ್ಯಾಮೆರಾ)',

    selectBorrower: 'ಸಾಲಗಾರರನ್ನು ಆಯ್ಕೆಮಾಡಿ', noActiveLoans: 'ಸಕ್ರಿಯ ಸಾಲಗಳಿಲ್ಲ. ಮೊದಲು ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ.',
    searchNameLocation: 'ಹೆಸರು ಅಥವಾ ಸ್ಥಳ ಹುಡುಕಿ...', noMembersMatch: 'ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದುವ ಸದಸ್ಯರಿಲ್ಲ.',
    capturePayment: 'ಪಾವತಿ ದಾಖಲಿಸಿ', statusColon: 'ಸ್ಥಿತಿ:', recoveryProgress: 'ಮರುಪಡೆಯುವಿಕೆ ಪ್ರಗತಿ',
    principalAmount: 'ಅಸಲು ಮೊತ್ತ', totalDueLabel: 'ಒಟ್ಟು ಬಾಕಿ', recovered: 'ಮರುಪಡೆಯಲಾಗಿದೆ',
    outstandingBalance: 'ಬಾಕಿ ಶಿಲ್ಕು', paymentDetails: 'ಪಾವತಿ ವಿವರಗಳು', cashFlow: 'ನಗದು ಹರಿವು', upiGpay: 'UPI / GPay',
    processing: 'ಪ್ರಕ್ರಿಯೆಗೊಳ್ಳುತ್ತಿದೆ...', record: 'ದಾಖಲಿಸಿ', payment: 'ಪಾವತಿ',

    ledgerBook: 'ಲೆಡ್ಜರ್ ಪುಸ್ತಕ', settled: 'ಇತ್ಯರ್ಥಗೊಂಡಿದೆ', principalColon: 'ಅಸಲು:', paidColon: 'ಪಾವತಿಸಿದ್ದು:',
    noLedgerEntries: 'ಇನ್ನೂ ಲೆಡ್ಜರ್ ನಮೂದುಗಳಿಲ್ಲ',

    paymentRecorded: 'ಪಾವತಿ ದಾಖಲಾಗಿದೆ!', savedSuccessfully: 'ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ', remainingBalance: 'ಉಳಿದ ಶಿಲ್ಕು',
    loanFullyPaid: 'ಸಾಲ ಸಂಪೂರ್ಣವಾಗಿ ಪಾವತಿಸಲಾಗಿದೆ!', sendWhatsappNotifications: 'ವಾಟ್ಸಾಪ್ ಅಧಿಸೂಚನೆಗಳನ್ನು ಕಳುಹಿಸಿ',
    notifyAdminWhatsapp: 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಅಡ್ಮಿನ್‌ಗೆ ತಿಳಿಸಿ', confirmToBorrower: 'ಸಾಲಗಾರರಿಗೆ ದೃಢೀಕರಿಸಿ', messagePreview: 'ಸಂದೇಶ ಪೂರ್ವವೀಕ್ಷಣೆ',
    recordAnotherPayment: 'ಇನ್ನೊಂದು ಪಾವತಿಯನ್ನು ದಾಖಲಿಸಿ', collectPaymentTitle: 'ಪಾವತಿ ಸಂಗ್ರಹಿಸಿ', asRole: 'ಆಗಿ', sort: 'ವಿಂಗಡಿಸಿ',
    noActiveLoansFound: 'ಸಕ್ರಿಯ ಸಾಲಗಳು ಕಂಡುಬಂದಿಲ್ಲ.', noBorrowersMatch: 'ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದುವ ಸಾಲಗಾರರಿಲ್ಲ.', balance: 'ಶಿಲ್ಕು',
    collectorYou: 'ಕಲೆಕ್ಟರ್ (ನೀವು)', notesOptional: 'ಟಿಪ್ಪಣಿಗಳು (ಐಚ್ಛಿಕ)', saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...', cash: 'ನಗದು', gpayUpi: 'GPay / UPI',
    noPhone: 'ಫೋನ್ ಇಲ್ಲ', dueColon: 'ಬಾಕಿ:', callBorrower: 'ಸಾಲಗಾರರಿಗೆ ಕರೆ ಮಾಡಿ', call: 'ಕರೆ', paymentEntry: 'ಪಾವತಿ ನಮೂದು',

    myCollections: 'ನನ್ನ ಸಂಗ್ರಹಗಳು', allPaymentsRecorded: 'ನೀವು ದಾಖಲಿಸಿದ ಎಲ್ಲಾ ಪಾವತಿಗಳು', entriesLabel: 'ನಮೂದುಗಳು',
    noCollectionsYet: 'ಇನ್ನೂ ಸಂಗ್ರಹಗಳು ದಾಖಲಾಗಿಲ್ಲ. ಸಂಗ್ರಹಿಸಲು ಪ್ರಾರಂಭಿಸಿ!', loadingHistory: 'ನಿಮ್ಮ ಸಂಗ್ರಹ ಇತಿಹಾಸ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',

    newBorrowerLoan: 'ಹೊಸ ಸಾಲಗಾರ + ಸಾಲ', requiredNote: '* = ಅಗತ್ಯ', personalDetails: 'ವೈಯಕ್ತಿಕ ವಿವರಗಳು',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು *', shopBusinessName: 'ಅಂಗಡಿ / ವ್ಯಾಪಾರ ಹೆಸರು', primaryMobile: 'ಪ್ರಾಥಮಿಕ ಮೊಬೈಲ್ *',
    alternateMobile: 'ಪರ್ಯಾಯ ಮೊಬೈಲ್', areaInCoimbatore: 'ಕೊಯಮತ್ತೂರಿನಲ್ಲಿ ಪ್ರದೇಶ *', verifyPhoneOtp: 'OTP ಮೂಲಕ ಫೋನ್ ಪರಿಶೀಲಿಸಿ (ಐಚ್ಛಿಕ)',
    phoneVerified: 'ಫೋನ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ', email: 'ಇಮೇಲ್', aadhaarNumber: 'ಆಧಾರ್ ಸಂಖ್ಯೆ', address: 'ವಿಳಾಸ',
    guarantorDetails: 'ಜಾಮೀನುದಾರ ವಿವರಗಳು', guarantorName: 'ಜಾಮೀನುದಾರ ಹೆಸರು', guarantorPhone: 'ಜಾಮೀನುದಾರ ಫೋನ್',
    guarantorAddress: 'ಜಾಮೀನುದಾರ ವಿಳಾಸ', loanDetails: 'ಸಾಲದ ವಿವರಗಳು', loanAmount: 'ಸಾಲದ ಮೊತ್ತ (₹) *',
    charges: 'ಶುಲ್ಕಗಳು (%)', chargesAmount: 'ಶುಲ್ಕದ ಮೊತ್ತ (₹)', auto: 'ಸ್ವಯಂಚಾಲಿತ', startDate: 'ಪ್ರಾರಂಭ ದಿನಾಂಕ *', dueDate: 'ಬಾಕಿ ದಿನಾಂಕ *',
    chargesAndFees: 'ಶುಲ್ಕಗಳು ಮತ್ತು ಫೀಸುಗಳು (₹)', autoSplitNote: 'ಶುಲ್ಕಗಳಿಂದ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ವಿಭಜಿಸಲಾಗಿದೆ — ಬಡ್ಡಿ 18%, ಫೀಲ್ಡ್ ವೆರಿಫಿಕೇಶನ್ 31%, ಡಾಕ್ಯುಮೆಂಟ್ ಶುಲ್ಕ 30%, ಪ್ರೊಸೆಸಿಂಗ್ ಶುಲ್ಕ 21%. ಈ ಸಾಲಕ್ಕೆ ಬೇರೆ ಮೊತ್ತಗಳು ಬೇಕಿದ್ದರೆ ಕೆಳಗೆ ಸರಿಹೊಂದಿಸಿ.',
    fieldVerification: 'ಫೀಲ್ಡ್ ವೆರಿಫಿಕೇಶನ್', documentFee: 'ಡಾಕ್ಯುಮೆಂಟ್ ಶುಲ್ಕ', processingFee: 'ಪ್ರೊಸೆಸಿಂಗ್ ಶುಲ್ಕ',
    breakdown: 'ವಿಭಜನೆ', principalLoanAmount: 'ಅಸಲು (ಸಾಲದ ಮೊತ್ತ)', ofWhich: 'ಇದರಲ್ಲಿ',
    deductedUpfront: 'ಅಸಲಿನಿಂದ ಮುಂಚಿತವಾಗಿ ಕಡಿತಗೊಳಿಸಲಾಗಿದೆ', cashDisbursedToBorrower: 'ಸಾಲಗಾರರಿಗೆ ನೀಡಿದ ನಗದು',
    totalDueRepayable: 'ಒಟ್ಟು ಬಾಕಿ (ಮರುಪಾವತಿಸಬೇಕಾದದ್ದು)', repaymentSchedule: 'ಮರುಪಾವತಿ ವೇಳಾಪಟ್ಟಿ', amountPerInstallment: 'ಪ್ರತಿ ಕಂತಿಗೆ ಮೊತ್ತ (₹)',
    disbursementSmsLanguage: 'ವಿತರಣೆ SMS ಭಾಷೆ', autoWhatsappReminders: 'ಸ್ವಯಂಚಾಲಿತ ವಾಟ್ಸಾಪ್ ಜ್ಞಾಪನೆಗಳು',
    confirmLoanDisbursal: 'ಸಾಲ ವಿತರಣೆಯನ್ನು ದೃಢೀಕರಿಸಿ', creating: 'ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    existingBorrower: 'ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಸಾಲಗಾರ', newBorrower: 'ಹೊಸ ಸಾಲಗಾರ', selectZone: 'ಪ್ರದೇಶವನ್ನು ಆಯ್ಕೆಮಾಡಿ…',
    mergeBorrowers: 'ಸಾಲಗಾರರನ್ನು ವಿಲೀನಗೊಳಿಸಿ', merge: 'ವಿಲೀನಗೊಳಿಸಿ', mergeSelected: 'ಆಯ್ಕೆ ಮಾಡಿದವರನ್ನು ವಿಲೀನಗೊಳಿಸಿ',
    noBorrowersYet: 'ಇನ್ನೂ ಸಾಲಗಾರರಿಲ್ಲ. ಸೇರಿಸಲು + ಒತ್ತಿ.', highestBalance: 'ಅತಿ ಹೆಚ್ಚು ಶಿಲ್ಕು', nameAZ: 'ಹೆಸರು A-Z',
    byArea: 'ಕೊಯಮತ್ತೂರು ಪ್ರದೇಶವಾರು', newestFirst: 'ಇತ್ತೀಚಿನದು ಮೊದಲು', due: 'ಬಾಕಿ', paidSuffix: 'ಪಾವತಿಸಲಾಗಿದೆ',
    loanDisbursed: 'ಸಾಲ ವಿತರಿಸಲಾಗಿದೆ!', borrowerAccountNumber: 'ಸಾಲಗಾರ ಖಾತೆ ಸಂಖ್ಯೆ', done: 'ಮುಗಿದಿದೆ',
    noPhoneSmsUnavailable: 'ಫೋನ್ ಸಂಖ್ಯೆ ಇಲ್ಲ — SMS ಲಭ್ಯವಿಲ್ಲ.',
    freqCustom: 'ಕಸ್ಟಮ್', freqDailyDesc: 'ಪ್ರತಿದಿನ ಸಂಗ್ರಹಿಸಲಾಗುತ್ತದೆ', freqWeeklyDesc: 'ವಾರಕ್ಕೊಮ್ಮೆ',
    freqMonthlyDesc: 'ತಿಂಗಳಿಗೊಮ್ಮೆ', freqCustomDesc: 'ನಿಮ್ಮ ಸ್ವಂತ ಮೊತ್ತವನ್ನು ಹೊಂದಿಸಿ',
    otpSending: 'ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…', sendOtpToVerifyPhone: 'ಫೋನ್ ಪರಿಶೀಲಿಸಲು OTP ಕಳುಹಿಸಿ', testOtpLabel: 'ಟೆಸ್ಟ್ OTP:',
    otpVerifying: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…', verifyOtpBtn: 'OTP ಪರಿಶೀಲಿಸಿ',
    mergeBorrowersDesc: 'ವಿಲೀನಗೊಳಿಸಲು ನಿಖರವಾಗಿ 2 ಸಾಲಗಾರರನ್ನು ಆಯ್ಕೆಮಾಡಿ. ಅವರ ಸಾಲ ದಾಖಲೆಗಳನ್ನು ಮೊದಲು ಆಯ್ಕೆ ಮಾಡಿದವರ ಅಡಿಯಲ್ಲಿ ಸಂಯೋಜಿಸಲಾಗುತ್ತದೆ.',
    outstandingColon: 'ಬಾಕಿ:', disbursedTo: 'ಗೆ ವಿತರಿಸಲಾಗಿದೆ', disbursementSms: 'ವಿತರಣೆ SMS',
    sendSmsToBorrower: 'ಸಾಲಗಾರರಿಗೆ SMS ಕಳುಹಿಸಿ',
  },
  ml: {
    appName: 'വസൂൽപ്രോ', appTagline: 'മൈക്രോ ഫിനാൻസ് സിസ്റ്റം',
    navMain: 'പ്രധാനം', navFinance: 'ധനകാര്യം', navSystem: 'സിസ്റ്റം', navCollector: 'കളക്ടർ',
    dashboard: 'ഡാഷ്ബോർഡ്', borrowers: 'വായ്പക്കാർ', collection: 'പിരിവ്', ledger: 'ലെഡ്ജർ',
    expenses: 'ചെലവുകൾ', reports: 'റിപ്പോർട്ടുകൾ', staff: 'ജീവനക്കാർ', settings: 'ക്രമീകരണങ്ങൾ',
    collectPayment: 'പേയ്‌മെന്റ് ശേഖരിക്കുക', history: 'ചരിത്രം', profile: 'പ്രൊഫൈൽ', transactions: 'ഇടപാടുകൾ',
    home: 'ഹോം', collect: 'ശേഖരിക്കുക', more: 'കൂടുതൽ', logout: 'ലോഗ്ഔട്ട്', language: 'ഭാഷ',
    notifications: 'അറിയിപ്പുകൾ', today: 'ഇന്ന്', settingsComingSoon: 'ക്രമീകരണങ്ങൾ ഉടൻ വരുന്നു',
    welcomeBack: 'ലേക്ക് വീണ്ടും സ്വാഗതം', helloGreeting: 'നമസ്കാരം', searchBorrowers: 'വായ്പക്കാരെ തിരയുക...',
    collectedToday: 'ഇന്ന് ശേഖരിച്ചത്', newLoan: 'പുതിയ വായ്പ', addBorrower: 'വായ്പക്കാരനെ ചേർക്കുക',
    todaysCollection: 'ഇന്നത്തെ പിരിവ്', activeBorrowers: 'സജീവ വായ്പക്കാർ',
    totalOutstanding: 'ആകെ കുടിശ്ശിക', totalCollected: 'ആകെ ശേഖരിച്ചത്',
    dueToday: 'ഇന്ന് അടയ്ക്കേണ്ടത്', overdueAlerts: 'കാലതാമസ മുന്നറിയിപ്പുകൾ', seeAll: 'എല്ലാം കാണുക',
    borrowersAndLoans: 'വായ്പക്കാരും വായ്പകളും', allAreas: 'എല്ലാ പ്രദേശങ്ങളും',
    welcome: 'സ്വാഗതം!', howLogin: 'നിങ്ങൾക്ക് എങ്ങനെ ലോഗിൻ ചെയ്യണം?',
    imAdmin: 'ഞാൻ അഡ്മിൻ ആണ്', imCollector: 'ഞാൻ കളക്ടർ ആണ്',
    sendOtp: 'OTP അയയ്ക്കുക', verifySignIn: 'സ്ഥിരീകരിച്ച് സൈൻ ഇൻ ചെയ്യുക', enterOtp: 'OTP നൽകുക', back: 'തിരികെ',

    ledgerPageTitle: 'പിരിവ് ലെഡ്ജർ', entriesSuffix: 'എൻട്രികൾ', allStaff: 'എല്ലാ ജീവനക്കാരും', recordPayment: 'പേയ്‌മെന്റ് രേഖപ്പെടുത്തുക',
    amountReceived: 'ലഭിച്ച തുക (₹)', penaltyLateFee: 'പിഴ / വൈകിയ ഫീസ് (₹)', confirmPayment: 'പേയ്‌മെന്റ് സ്ഥിരീകരിക്കുക',
    totalDueToday: 'ഇന്ന് ആകെ അടയ്ക്കേണ്ടത്', collectedLabel: 'ശേഖരിച്ചത്', pendingLabel: 'ബാക്കി', collectionPercent: 'പിരിവ് %',
    collectionProgress: 'പിരിവ് പുരോഗതി', daily: 'ദിവസേന', weekly: 'ആഴ്ചതോറും', monthly: 'മാസംതോറും', allDue: 'എല്ലാ ബാക്കിയും',
    tableBorrower: 'വായ്പക്കാരൻ', tablePhone: 'ഫോൺ', tableType: 'തരം', tableDueAmount: 'ബാക്കി തുക', tablePaid: 'അടച്ചത്',
    tableStatus: 'നില', tableStaff: 'ജീവനക്കാരൻ', tableAction: 'നടപടി', noInstallmentsDue: 'ഈ ഫിൽട്ടറിന് ഗഡുക്കളൊന്നും ബാക്കിയില്ല',
    statusPaid: 'അടച്ചു', statusPartial: 'ഭാഗികം', statusPending: 'ബാക്കി', statusOverdue: 'കാലതാമസം',
    modeFull: 'പൂർണ്ണം', modePartial: 'ഭാഗികം', modeAdvance: 'അഡ്വാൻസ്',

    expensesAndCapital: 'ചെലവുകളും മൂലധനവും', businessFinancialHealth: 'ബിസിനസ് സാമ്പത്തിക നിലയുടെ അവലോകനം',
    logInvestment: 'നിക്ഷേപം രേഖപ്പെടുത്തുക', addExpense: 'ചെലവ് ചേർക്കുക', totalInvested: 'ആകെ നിക്ഷേപം', totalExpenses: 'ആകെ ചെലവുകൾ',
    capitalInvestments: 'മൂലധന നിക്ഷേപങ്ങൾ', logExpense: 'ചെലവ് രേഖപ്പെടുത്തുക', category: 'വിഭാഗം', amountRs: 'തുക (₹)',
    dateLabel: 'തീയതി', descriptionLabel: 'വിവരണം', logCapitalInvestment: 'മൂലധന നിക്ഷേപം രേഖപ്പെടുത്തുക',
    amountInvested: 'നിക്ഷേപിച്ച തുക (₹)', noteLabel: 'കുറിപ്പ്',

    financialReports: 'സാമ്പത്തിക റിപ്പോർട്ടുകൾ', analyticsExportCenter: 'വിശകലനവും എക്സ്പോർട്ട് കേന്ദ്രവും', excel: 'എക്സൽ', pdfReport: 'PDF റിപ്പോർട്ട്',
    reportPL: 'ലാഭനഷ്ടം', reportPLDesc: 'വരുമാനവും ചെലവുകളും', reportCollection: 'പിരിവ് സംഗ്രഹം',
    reportCollectionDesc: 'ദിവസംതോറുമുള്ള പിരിവ് പ്രകടനം', reportPortfolio: 'വായ്പ പോർട്ട്‌ഫോളിയോ',
    reportPortfolioDesc: 'തരവും നിലയും അനുസരിച്ച് സജീവ വായ്പകൾ', reportOverdue: 'കാലതാമസ റിപ്പോർട്ട്',
    reportOverdueDesc: 'എല്ലാ കാലതാമസ അക്കൗണ്ടുകളും കാലയളവും', grossRevenue: 'മൊത്ത വരുമാനം',
    grossRevenueNote: 'ആകെ പലിശ + മുതൽ ശേഖരിച്ചത്', totalExpensesNote: 'ശമ്പളം, ഇന്ധനം, ഓഫീസ്, മറ്റുള്ളവ',
    outstandingLabel: 'കുടിശ്ശിക', outstandingNote: 'തിരിച്ചുപിടിക്കേണ്ട ബാക്കി തുക', tableDay: 'ദിവസം', tableTarget: 'ലക്ഷ്യം',
    tableAchievement: 'നേട്ടം', tablePrincipal: 'മുതൽ', tableTotalDue: 'ആകെ ബാക്കി', statusActive: 'സജീവം',
    statusClosed: 'അടച്ചു', statusDefaulted: 'ഡിഫോൾട്ട്', loansSuffix: 'വായ്പകൾ', noOverdueAccounts: 'കാലതാമസ അക്കൗണ്ടുകൾ ഇല്ല!',
    tableDueDate: 'അടയ്ക്കേണ്ട തീയതി', tableAmountDue: 'ബാക്കി തുക', tableDaysOverdue: 'കാലതാമസ ദിവസങ്ങൾ', daysSuffix: 'ദിവസങ്ങൾ',

    staffManagement: 'ജീവനക്കാരുടെ മാനേജ്മെന്റ്', teamMembers: 'ടീം അംഗങ്ങൾ', rbacEnabled: 'RBAC പ്രവർത്തനക്ഷമം', addStaff: 'ജീവനക്കാരനെ ചേർക്കുക',
    addStaffMember: 'ജീവനക്കാരനെ ചേർക്കുക', fullNameRequired: 'മുഴുവൻ പേര് *', role: 'റോൾ', roleAdmin: 'അഡ്മിൻ', roleManager: 'മാനേജർ',
    roleCollector: 'കളക്ടർ', phone: 'ഫോൺ', monthlyTarget: 'മാസ ലക്ഷ്യം (₹)', efficiency: 'കാര്യക്ഷമത', target: 'ലക്ഷ്യം',
    loans: 'വായ്പകൾ', rolePermissionMatrix: 'റോൾ അനുമതി മാട്രിക്സ്', permission: 'അനുമതി', permViewDashboard: 'ഡാഷ്ബോർഡ് കാണുക',
    permCreateLoans: 'വായ്പകൾ സൃഷ്ടിക്കുക', permCollectPayments: 'പേയ്‌മെന്റുകൾ ശേഖരിക്കുക', permViewReports: 'റിപ്പോർട്ടുകളും ലാഭനഷ്ടവും കാണുക',
    permManageStaff: 'ജീവനക്കാരെ നിയന്ത്രിക്കുക', permDeleteRecords: 'രേഖകൾ ഇല്ലാതാക്കുക', permExportData: 'ഡാറ്റ എക്സ്പോർട്ട് ചെയ്യുക',
    permViewCapital: 'മൂലധനം/നിക്ഷേപം കാണുക', recentAuditLog: 'സമീപകാല ഓഡിറ്റ് ലോഗ്',

    myProfile: 'എന്റെ പ്രൊഫൈൽ', verified: 'സ്ഥിരീകരിച്ചു', contactInformation: 'ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ', emailAddress: 'ഇമെയിൽ വിലാസം',
    phoneNumber: 'ഫോൺ നമ്പർ', homeAddress: 'വീട്ടു വിലാസം', financeAndProofs: 'ധനകാര്യവും തെളിവുകളും',
    linkedBankAccount: 'ലിങ്ക് ചെയ്ത ബാങ്ക് അക്കൗണ്ട്', mandatoryProofKyc: 'നിർബന്ധിത തെളിവ് കോപ്പി (KYC)', notYetUploaded: 'ഇതുവരെ അപ്‌ലോഡ് ചെയ്തിട്ടില്ല',
    upload: 'അപ്‌ലോഡ് ചെയ്യുക', loginHistory: 'ലോഗിൻ ചരിത്രം', signOutSafely: 'സുരക്ഷിതമായി സൈൻ ഔട്ട് ചെയ്യുക', loadingProfile: 'പ്രൊഫൈൽ ലോഡ് ചെയ്യുന്നു...',

    uploadBtn: 'അപ്‌ലോഡ് ചെയ്യുക', cameraBtn: 'ക്യാമറ', removeBtn: 'നീക്കം ചെയ്യുക', takePhoto: 'ഫോട്ടോ എടുക്കുക', retake: 'വീണ്ടും എടുക്കുക',
    usePhoto: 'ഫോട്ടോ ഉപയോഗിക്കുക', flip: 'തിരിക്കുക', capture: 'ക്യാപ്ചർ ചെയ്യുക',
    cameraNotSupported: 'ഈ ഉപകരണത്തിൽ/ബ്രൗസറിൽ ക്യാമറ പിന്തുണയ്ക്കുന്നില്ല. ദയവായി അപ്‌ലോഡ് ഉപയോഗിക്കുക.',
    cameraPermissionDenied: 'ക്യാമറ അനുമതി നിഷേധിച്ചു. ക്യാമറ ആക്സസ് അനുവദിക്കുക അല്ലെങ്കിൽ അപ്‌ലോഡ് ഉപയോഗിക്കുക.',
    cameraAccessError: 'ക്യാമറ ആക്സസ് ചെയ്യാനായില്ല. ദയവായി അപ്‌ലോഡ് ഉപയോഗിക്കുക.',
    addPhotoDefault: 'ഫോട്ടോ ചേർക്കുക', addBorrowerPhoto: 'വായ്പക്കാരന്റെ ഫോട്ടോ ചേർക്കുക (അപ്‌ലോഡ് അല്ലെങ്കിൽ ക്യാമറ)', addPhotoUploadCamera: 'ഫോട്ടോ ചേർക്കുക (അപ്‌ലോഡ് അല്ലെങ്കിൽ ക്യാമറ)',

    selectBorrower: 'വായ്പക്കാരനെ തിരഞ്ഞെടുക്കുക', noActiveLoans: 'സജീവ വായ്പകൾ ഇല്ല. ആദ്യം അംഗങ്ങളെ ചേർക്കുക.',
    searchNameLocation: 'പേരോ സ്ഥലമോ തിരയുക...', noMembersMatch: 'നിങ്ങളുടെ തിരയലുമായി പൊരുത്തപ്പെടുന്ന അംഗങ്ങളില്ല.',
    capturePayment: 'പേയ്‌മെന്റ് രേഖപ്പെടുത്തുക', statusColon: 'നില:', recoveryProgress: 'വീണ്ടെടുക്കൽ പുരോഗതി',
    principalAmount: 'മുതൽ തുക', totalDueLabel: 'ആകെ ബാക്കി', recovered: 'വീണ്ടെടുത്തത്',
    outstandingBalance: 'ബാക്കി ബാലൻസ്', paymentDetails: 'പേയ്‌മെന്റ് വിവരങ്ങൾ', cashFlow: 'ക്യാഷ് ഫ്ലോ', upiGpay: 'UPI / GPay',
    processing: 'പ്രോസസ് ചെയ്യുന്നു...', record: 'രേഖപ്പെടുത്തുക', payment: 'പേയ്‌മെന്റ്',

    ledgerBook: 'ലെഡ്ജർ ബുക്ക്', settled: 'തീർപ്പാക്കി', principalColon: 'മുതൽ:', paidColon: 'അടച്ചത്:',
    noLedgerEntries: 'ഇതുവരെ ലെഡ്ജർ എൻട്രികൾ ഇല്ല',

    paymentRecorded: 'പേയ്‌മെന്റ് രേഖപ്പെടുത്തി!', savedSuccessfully: 'വിജയകരമായി സേവ് ചെയ്തു', remainingBalance: 'ബാക്കിയുള്ള ബാലൻസ്',
    loanFullyPaid: 'വായ്പ പൂർണ്ണമായി അടച്ചു!', sendWhatsappNotifications: 'വാട്സ്ആപ്പ് അറിയിപ്പുകൾ അയയ്ക്കുക',
    notifyAdminWhatsapp: 'വാട്സ്ആപ്പിൽ അഡ്മിനെ അറിയിക്കുക', confirmToBorrower: 'വായ്പക്കാരന് സ്ഥിരീകരിക്കുക', messagePreview: 'സന്ദേശ പ്രിവ്യൂ',
    recordAnotherPayment: 'മറ്റൊരു പേയ്‌മെന്റ് രേഖപ്പെടുത്തുക', collectPaymentTitle: 'പേയ്‌മെന്റ് ശേഖരിക്കുക', asRole: 'ആയി', sort: 'ക്രമീകരിക്കുക',
    noActiveLoansFound: 'സജീവ വായ്പകൾ കണ്ടെത്തിയില്ല.', noBorrowersMatch: 'നിങ്ങളുടെ തിരയലുമായി പൊരുത്തപ്പെടുന്ന വായ്പക്കാരില്ല.', balance: 'ബാലൻസ്',
    collectorYou: 'കളക്ടർ (നിങ്ങൾ)', notesOptional: 'കുറിപ്പുകൾ (ഓപ്ഷണൽ)', saving: 'സേവ് ചെയ്യുന്നു...', cash: 'ക്യാഷ്', gpayUpi: 'GPay / UPI',
    noPhone: 'ഫോൺ ഇല്ല', dueColon: 'ബാക്കി:', callBorrower: 'വായ്പക്കാരനെ വിളിക്കുക', call: 'വിളിക്കുക', paymentEntry: 'പേയ്‌മെന്റ് എൻട്രി',

    myCollections: 'എന്റെ പിരിവുകൾ', allPaymentsRecorded: 'നിങ്ങൾ രേഖപ്പെടുത്തിയ എല്ലാ പേയ്‌മെന്റുകളും', entriesLabel: 'എൻട്രികൾ',
    noCollectionsYet: 'ഇതുവരെ പിരിവുകൾ രേഖപ്പെടുത്തിയിട്ടില്ല. ശേഖരിക്കാൻ തുടങ്ങുക!', loadingHistory: 'നിങ്ങളുടെ പിരിവ് ചരിത്രം ലോഡ് ചെയ്യുന്നു...',

    newBorrowerLoan: 'പുതിയ വായ്പക്കാരൻ + വായ്പ', requiredNote: '* = ആവശ്യമാണ്', personalDetails: 'വ്യക്തിഗത വിവരങ്ങൾ',
    fullName: 'മുഴുവൻ പേര് *', shopBusinessName: 'കട / ബിസിനസ് പേര്', primaryMobile: 'പ്രാഥമിക മൊബൈൽ *',
    alternateMobile: 'ബദൽ മൊബൈൽ', areaInCoimbatore: 'കോയമ്പത്തൂരിലെ പ്രദേശം *', verifyPhoneOtp: 'OTP വഴി ഫോൺ സ്ഥിരീകരിക്കുക (ഓപ്ഷണൽ)',
    phoneVerified: 'ഫോൺ സ്ഥിരീകരിച്ചു', email: 'ഇമെയിൽ', aadhaarNumber: 'ആധാർ നമ്പർ', address: 'വിലാസം',
    guarantorDetails: 'ജാമ്യക്കാരന്റെ വിവരങ്ങൾ', guarantorName: 'ജാമ്യക്കാരന്റെ പേര്', guarantorPhone: 'ജാമ്യക്കാരന്റെ ഫോൺ',
    guarantorAddress: 'ജാമ്യക്കാരന്റെ വിലാസം', loanDetails: 'വായ്പ വിവരങ്ങൾ', loanAmount: 'വായ്പ തുക (₹) *',
    charges: 'ചാർജുകൾ (%)', chargesAmount: 'ചാർജ് തുക (₹)', auto: 'ഓട്ടോ', startDate: 'ആരംഭ തീയതി *', dueDate: 'അടയ്ക്കേണ്ട തീയതി *',
    chargesAndFees: 'ചാർജുകളും ഫീസുകളും (₹)', autoSplitNote: 'ചാർജുകളിൽ നിന്ന് ഓട്ടോമാറ്റിക് ആയി വിഭജിച്ചത് — പലിശ 18%, ഫീൽഡ് വെരിഫിക്കേഷൻ 31%, ഡോക്യുമെന്റ് ഫീസ് 30%, പ്രോസസിംഗ് ഫീസ് 21%. ഈ വായ്പയ്ക്ക് വ്യത്യസ്ത തുകകൾ വേണമെങ്കിൽ താഴെ ക്രമീകരിക്കുക.',
    fieldVerification: 'ഫീൽഡ് വെരിഫിക്കേഷൻ', documentFee: 'ഡോക്യുമെന്റ് ഫീസ്', processingFee: 'പ്രോസസിംഗ് ഫീസ്',
    breakdown: 'വിഭജനം', principalLoanAmount: 'മുതൽ (വായ്പ തുക)', ofWhich: 'ഇതിൽ',
    deductedUpfront: 'മുതലിൽ നിന്ന് മുൻകൂട്ടി കുറച്ചത്', cashDisbursedToBorrower: 'വായ്പക്കാരന് നൽകിയ ക്യാഷ്',
    totalDueRepayable: 'ആകെ ബാക്കി (തിരിച്ചടയ്ക്കേണ്ടത്)', repaymentSchedule: 'തിരിച്ചടവ് ഷെഡ്യൂൾ', amountPerInstallment: 'ഓരോ ഗഡുവിനും തുക (₹)',
    disbursementSmsLanguage: 'വിതരണ SMS ഭാഷ', autoWhatsappReminders: 'ഓട്ടോ വാട്സ്ആപ്പ് ഓർമ്മപ്പെടുത്തലുകൾ',
    confirmLoanDisbursal: 'വായ്പ വിതരണം സ്ഥിരീകരിക്കുക', creating: 'സൃഷ്ടിക്കുന്നു...',
    existingBorrower: 'നിലവിലുള്ള വായ്പക്കാരൻ', newBorrower: 'പുതിയ വായ്പക്കാരൻ', selectZone: 'പ്രദേശം തിരഞ്ഞെടുക്കുക…',
    mergeBorrowers: 'വായ്പക്കാരെ ലയിപ്പിക്കുക', merge: 'ലയിപ്പിക്കുക', mergeSelected: 'തിരഞ്ഞെടുത്തവരെ ലയിപ്പിക്കുക',
    noBorrowersYet: 'ഇതുവരെ വായ്പക്കാരില്ല. ചേർക്കാൻ + അമർത്തുക.', highestBalance: 'ഏറ്റവും ഉയർന്ന ബാലൻസ്', nameAZ: 'പേര് A-Z',
    byArea: 'കോയമ്പത്തൂർ പ്രദേശം അനുസരിച്ച്', newestFirst: 'ഏറ്റവും പുതിയത് ആദ്യം', due: 'ബാക്കി', paidSuffix: 'അടച്ചു',
    loanDisbursed: 'വായ്പ വിതരണം ചെയ്തു!', borrowerAccountNumber: 'വായ്പക്കാരന്റെ അക്കൗണ്ട് നമ്പർ', done: 'പൂർത്തിയായി',
    noPhoneSmsUnavailable: 'ഫോൺ നമ്പർ ഇല്ല — SMS ലഭ്യമല്ല.',
    freqCustom: 'കസ്റ്റം', freqDailyDesc: 'ദിവസവും ശേഖരിക്കുന്നു', freqWeeklyDesc: 'ആഴ്ചയിൽ ഒരിക്കൽ',
    freqMonthlyDesc: 'മാസത്തിൽ ഒരിക്കൽ', freqCustomDesc: 'നിങ്ങളുടെ സ്വന്തം തുക സജ്ജമാക്കുക',
    otpSending: 'അയയ്ക്കുന്നു…', sendOtpToVerifyPhone: 'ഫോൺ സ്ഥിരീകരിക്കാൻ OTP അയയ്ക്കുക', testOtpLabel: 'ടെസ്റ്റ് OTP:',
    otpVerifying: 'സ്ഥിരീകരിക്കുന്നു…', verifyOtpBtn: 'OTP സ്ഥിരീകരിക്കുക',
    mergeBorrowersDesc: 'ലയിപ്പിക്കാൻ കൃത്യമായി 2 വായ്പക്കാരെ തിരഞ്ഞെടുക്കുക. അവരുടെ വായ്പാ രേഖകൾ ആദ്യം തിരഞ്ഞെടുത്തതിന് കീഴിൽ സംയോജിപ്പിക്കും.',
    outstandingColon: 'കുടിശ്ശിക:', disbursedTo: 'ന് വിതരണം ചെയ്തു', disbursementSms: 'വിതരണ SMS',
    sendSmsToBorrower: 'വായ്പക്കാരന് SMS അയയ്ക്കുക',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem(STORAGE_KEY) || 'en');

  const setLanguage = useCallback((lang) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  }, []);

  const t = useCallback((key) => {
    return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
